"""CJK→English phrase mappings for MPP technical documentation.

Organised in passes — earlier passes handle large multi-word chunks,
later passes clean up single-character remnants.  Add new phrases at the
top of the appropriate pass; the runner applies passes in order.
"""

PASS_1 = [
    # ── Multi-word fixed expressions (longest first to avoid partial matches) ──
    ("同步信号配置时序图", "Sync Signal Configuration Timing Diagram"),
    ("同步信号极性翻转", "Sync Signal Polarity Inversion"),
    ("白色区域选择相关参数", "White Region Selection Parameters"),
    ("接口调用流程", "API Call Flow"),
    ("几何畸变矫正子系统", "Geometric Distortion Correction Subsystem"),
    ("视频处理子系统", "Video Processing Subsystem"),
    ("视频图形子系统", "Video Graphics Subsystem"),
    ("视频编码模块", "Video Encoding Module"),
    ("视频解码模块", "Video Decoding Module"),
    ("视频输入模块", "Video Input Module"),
    ("视频输出模块", "Video Output Module"),
    ("音频输入输出", "Audio Input/Output"),
    ("音频编码解码", "Audio Encode/Decode"),
    ("区域管理", "Region Management"),
    ("系统控制", "System Control"),
    ("开机画面", "Splash Screen"),
    ("回到页面顶部", "Back to top"),
    ("媒体处理软件", "Media Processing Software"),
    ("开发参考", "Development Reference"),
    ("调试信息", "Debug Information"),
    ("注意事项", "Notes"),
    ("基本概念", "Basic Concepts"),
    ("功能描述", "Functional Description"),
    ("相关主题", "Related Topics"),
    ("数据类型", "Data Types"),
    ("错误码", "Error Codes"),
    ("取值范围", "Value range"),
    ("默认值", "Default value"),
    ("返回值", "Return value"),
    ("输入参数", "Input parameter"),
    ("输出参数", "Output parameter"),
    ("解决方案", "Solution"),
    ("应用程序", "Application"),
    ("文件系统", "File System"),
    ("文件目录", "File Directory"),
    ("参考信息", "Reference Information"),
    ("软件开发包", "Software Development Kit"),
    ("比特流", "Bitstream"),
    ("像素格式", "Pixel Format"),
    ("格式转换", "Format Conversion"),
    ("非直通", "Non-pass-through"),
    ("幅型比", "Aspect Ratio"),
    ("前置分频", "Pre-divider"),
    ("时钟分频比", "Clock Division Ratio"),
    ("解压规格", "Decompression Specification"),
    ("分频系数", "Division Coefficient"),
    ("聚集内存", "Gathered Memory"),
    ("非聚集内存", "Non-gathered Memory"),
    ("局部放大", "Local Zoom"),
    ("抗闪", "Anti-flicker"),
    ("非融合拼接", "Non-blending Splicing"),
    ("全景拼接", "Panoramic Splicing"),
    ("投影模式", "Projection Mode"),
    ("田字形", "Grid Pattern"),
    ("角框", "Corner Rectangle"),
    ("遮挡", "Cover"),
    ("色块", "Color Block"),
    ("画线", "Line Drawing"),
    ("展宽", "Stretch"),
    ("鱼眼矫正", "Fisheye Correction"),
    ("镜头畸变校正", "Lens Distortion Correction"),
    ("背景色", "Background Color"),
    ("标定", "Calibration"),
    ("非融合", "Non-blending"),
    ("去隔行", "Deinterlace"),
    ("固定角度旋转", "Fixed-angle Rotation"),
    ("任意角度旋转", "Arbitrary-angle Rotation"),
    ("区域亮度和", "Region Luminance Sum"),
    ("低延时", "Low Latency"),
    ("动态范围压缩", "Dynamic Range Compression"),
    ("曝光比切换", "Exposure Ratio Switching"),
    ("模式切换", "Mode Switching"),
    ("送帧间隔", "Frame Delivery Interval"),
    ("中断下半部", "Interrupt Bottom Half"),
    ("中断服务程序", "Interrupt Service Routine"),
    ("同步寄存器", "Synchronization Register"),
    ("物理管道", "Physical Pipe"),
    ("白平衡", "White Balance"),
    ("自动曝光", "Auto Exposure"),
    ("自动对焦", "Auto Focus"),
    ("算法模块", "Algorithm Module"),
    ("省BUF", "Buffer-saving"),
    ("同源输出", "Same-source Output"),
    ("互斥接口", "Mutually Exclusive Interface"),
    ("分频比", "Division Ratio"),
    ("相位反向", "Phase Inversion"),
    ("外设", "Peripheral"),
    ("前置", "Pre-"),
    ("回写模式", "Writeback Mode"),
    ("回写源", "Writeback Source"),
    ("显示帧率", "Display Frame Rate"),
    ("重复显示", "Repeated Display"),
    ("逐行显示", "Progressive Display"),
    ("隔行图像", "Interlaced Image"),
    ("监视器", "Monitor"),
    ("单区域", "Single Region"),
    ("多区域", "Multiple Regions"),
    ("手动模式", "Manual Mode"),
    ("自动模式", "Auto Mode"),
    ("显示区域", "Display Region"),
    ("重叠", "Overlap"),
    ("覆盖", "Override"),
    ("省", "Save"),
    ("私有", "Private"),
    ("轮转", "Rotation Buffer"),
    ("绑定", "Bind"),
    ("解绑", "Unbind"),
    ("压缩模式", "Compression Mode"),
    ("行压", "Line Compression"),
    ("非压", "No Compression"),
    ("直通", "Pass-through"),
    ("拼接模式", "Splicing Mode"),
    ("输入/输出", "Input/Output"),
    ("开发环境", "Development Environment"),
    ("交叉编译器", "Cross Compiler"),
    ("开源软件", "Open Source Software"),
    ("代码仓", "Code Repository"),
    ("编译", "Compilation"),
    ("烧写", "Flashing"),
    ("烧录", "Burning"),
    ("基础环境", "Base Environment"),
    ("搭建", "Set Up"),
    ("下载", "Download"),
    ("安装", "Install"),
    ("快速开始", "Quick Start"),
    ("快速启动", "Quick Start"),
    ("选择开发板", "Choose a Development Board"),
    ("选择操作系统", "Choose an Operating System"),
    ("安装开发环境", "Set Up the Development Environment"),
    ("安装 SDK", "Install the SDK"),
    ("驱动安装", "Driver Installation"),
    ("上游 SDK 快速开始", "Upstream SDK Quick Start"),
    ("拖尾", "Smearing"),
    ("背景", "Background"),
    ("滤波", "Filtering"),
    ("物体", "Object"),
    ("导致", "Causes"),
    ("波动", "Fluctuation"),
    ("约束", "Constraint"),
    ("陀螺", "Gyroscope"),
    ("损失", "Loss"),
    ("复杂", "Complex"),
    ("自己", "Self"),
    ("功耗", "Power Consumption"),
    ("道静音", "Channel Mute"),
    ("保留", "Reserved"),
    ("幅形", "Aspect"),
    ("启动", "Startup"),
    ("现象", "Phenomenon"),
    ("面积", "Area"),
    ("边缘", "Edge"),
    ("消耗", "Consumption"),
    ("累计", "Cumulative"),
    ("播放", "Playback"),
    ("预览", "Preview"),
    ("基础", "Basic"),
    ("语音", "Voice"),
    ("直接", "Directly"),
    ("互斥", "Mutually Exclusive"),
    ("公式", "Formula"),
    ("说明", "Description"),
    ("位倒", "Bit Reversal"),
    ("文件", "File"),
    ("普通", "Normal"),
    ("尺寸筛选", "Size Filtering"),
    ("产生", "Generate"),
    ("独立", "Independent"),
    ("映射", "Mapping"),
    ("含义", "Meaning"),
    ("产品形", "Product Shape"),
    ("矩形", "Rectangle"),
    ("任何", "Any"),
    ("结束", "End"),
    ("平坦", "Flat"),
    ("曲线", "Curve"),
    ("间预", "Inter Prediction"),
    ("剩余", "Remaining"),
    ("静音", "Mute"),
    ("改善", "Improve"),
    ("指南", "Guide"),
    ("业务", "Service"),
    ("采样", "Sampling"),
    ("保持", "Maintain"),
    ("方法", "Method"),
    ("风险", "Risk"),
    ("请见", "See"),
    ("确保", "Ensure"),
    ("生成", "Generate"),
    ("造成", "Cause"),
    ("采集", "Capture"),
    ("任意", "Arbitrary"),
    ("依然", "Still"),
    ("简称", "Abbreviation"),
    ("纯色填", "Solid Color Fill"),
    ("频繁", "Frequent"),
    ("感兴趣", "Interest"),
    ("详细", "Detailed"),
    ("录像机", "Video Recorder"),
    ("局样式", "Layout Style"),
    ("方案", "Solution"),
    ("概念", "Concept"),
    ("尺寸", "Size"),
    ("准确", "Accurate"),
    ("估算", "Estimation"),
    ("某些", "Certain"),
    ("避免带", "Avoid"),
    ("误差", "Error"),
    ("方差", "Variance"),
    ("状况", "Status"),
    ("桶形", "Barrel"),
    ("四周", "Surrounding"),
    ("反色", "Inverted Color"),
    ("掩码", "Mask"),
    ("因素", "Factor"),
    ("确性", "Accuracy"),
    ("冲突", "Conflict"),
    ("位管脚", "Bit Pin"),
    ("颜色", "Color"),
    ("精任意", "Arbitrary Precision"),
    ("继续", "Continue"),
    ("矢量", "Vector"),
    ("依次", "Sequential"),
    ("敏感", "Sensitive"),
    ("缩略", "Thumbnail"),
    ("音量", "Volume"),
    ("道音轨", "Channel Audio Track"),
    ("休眠", "Sleep"),
    ("通信", "Communication"),
    ("毫秒", "Milliseconds"),
    ("推荐", "Recommended"),
    ("避免", "Avoid"),
    ("工作", "Work"),
    ("串色", "Crosstalk"),
    ("预期", "Expected"),
    ("人机", "Human-Machine"),
    ("动幅", "Dynamic Range"),
    ("历史", "History"),
    ("传入", "Input"),
    ("总待", "Total Pending"),
    ("缓冲", "Buffer"),
    ("扩展", "Extension"),
    ("逻辑", "Logic"),
    ("改写", "Rewrite"),
    ("整体", "Overall"),
    ("副作", "Side Effect"),
    ("器保边", "Edge-Preserving Filter"),
    ("考虑", "Consider"),
    ("由五", "By Five"),
    ("由六", "By Six"),
    ("由四", "By Four"),
    ("填写", "Fill"),
    ("频带", "Frequency Band"),
    ("二次", "Secondary"),
    ("谐波", "Harmonic"),
    ("抗削波", "Anti-Clipping"),
    ("混响", "Reverberation"),
    ("降风", "Wind Noise Reduction"),
    ("桶型", "Barrel"),
    ("颗粒", "Grain"),
    ("代替", "Replace"),
    ("随意", "Arbitrary"),
    ("间戳", "Timestamp"),
    ("跟随", "Follow"),
    ("它们", "They"),
    ("自生", "Self-Generated"),
    ("浪费", "Waste"),
    ("拖拽", "Drag"),
    ("名称", "Name"),
    ("而言", "For"),
    ("样式", "Style"),
    ("量顺", "Order"),
    ("规格", "Specification"),
    ("代码", "Code"),
    ("筛选", "Filter"),
    ("条件", "Condition"),
    ("匹配", "Match"),
    ("锐利程", "Sharpness"),
    ("保边", "Edge-Preserving"),
    ("抑制", "Suppression"),
    ("化而", "Changes With"),
    ("接受", "Accept"),
    ("监听", "Monitor"),
    ("衡量", "Measure"),
    ("严格", "Strict"),
    ("化剧烈", "Drastic Change"),
    ("偏差", "Deviation"),
    ("解释", "Explain"),
    ("估计", "Estimate"),
    ("残差", "Residual"),
    ("亦然", "Likewise"),
    ("摄像机", "Camera"),
    ("典型", "Typical"),
    ("规律", "Pattern"),
    ("法性", "Legality"),
    ("现概", "Overview"),
    ("现整", "Adjustment"),
    ("刷成", "Refresh"),
    ("互质", "Coprime"),
    ("平稳性", "Stability"),
    ("频保", "Frequency Protection"),
    ("波衰", "Wave Attenuation"),
    ("平滑系", "Smoothing Coefficient"),
    ("倒谱平滑", "Cepstral Smoothing"),
    ("语法", "Syntax"),
    ("写头", "Write Head"),
    ("写尾", "Write Tail"),
    ("服务", "Service"),
    ("投影心", "Projection Center"),
    ("偏航", "Yaw"),
    ("俯仰", "Pitch"),
    ("翻滚", "Roll"),
    ("现耗", "Consumption"),
    ("项累", "Cumulative"),
    ("冻结", "Freeze"),
    ("请务", "Must"),
    ("纯色", "Solid Color"),
    ("里面", "Inside"),
    ("间插", "Interpolation"),
    ("景二", "Background"),
    ("文档", "Document"),
    ("拍照", "Photograph"),
    ("像素", "Pixel"),
    ("介绍", "Introduction"),
    ("手册", "Manual"),
    ("扫描", "Scan"),
    ("位反接", "Bit Reversal"),
    ("现像", "Phenomenon"),
    ("读入", "Read"),
    ("确哪", "Determine"),
    ("差距", "Difference"),
    ("接入", "Access"),
    ("四自", "Quad"),
    ("六自", "Hex"),
    ("想采", "Desired"),
    ("间差", "Time Difference"),
    ("微秒", "Microsecond"),
    ("传通", "Transmission"),
    ("互换", "Interchange"),
    ("初始", "Initial"),
    ("连接", "Connection"),
    # Single chars - end of PASS_1
    ("号", "No."),
    ("器", ""),
    ("性", ""),
    ("由", "by"),
    ("体", ""),
    ("第", ""),
    ("成", ""),
    ("位", "bit"),
    ("现", ""),
    ("道", "channel"),
    ("间", ""),
    ("程", ""),
    ("总", "total"),
    ("边", "edge"),
    ("法", ""),
    ("色", "color"),
    ("整", ""),
    ("项", ""),
    ("而", ""),
    ("送", "send"),
    ("编", "codec"),
    ("暂", "temporary"),
    ("运", ""),
    ("常", ""),
    ("差", ""),
    ("放", ""),
    ("刷", ""),
    ("得", ""),
    ("降", "reduce"),
    ("消", ""),
]

PASS_2 = [
    # ── Verbs ──
    ("表示", "Indicates"),
    ("用于", "Used for"),
    ("负责", "Responsible for"),
    ("实现", "Implements"),
    ("完成", "Completes"),
    ("进行", "Performs"),
    ("存在", "Exists"),
    ("使用", "Uses"),
    ("调用", "Calls"),
    ("返回", "Returns"),
    ("读取", "Reads"),
    ("写入", "Writes"),
    ("修改", "Modifies"),
    ("删除", "Deletes"),
    ("增加", "Increases"),
    ("减少", "Decreases"),
    ("保存", "Saves"),
    ("更新", "Updates"),
    ("检查", "Checks"),
    ("计算", "Calculates"),
    ("判断", "Determines"),
    ("选择", "Selects"),
    ("切换", "Switches"),
    ("转换", "Converts"),
    ("拷贝", "Copies"),
    ("移动", "Moves"),
    ("等待", "Waits"),
    ("通知", "Notifies"),
    ("无法", "Unable to"),
    ("不可", "Cannot"),
    ("不会", "Will not"),
    ("将会", "Will"),
    ("可能会", "May"),
    ("可用于", "Can be used for"),
    ("用来", "Used to"),
    ("用作", "Used as"),
    ("作为", "As"),
    ("称为", "Called"),
    ("对应", "Corresponding"),
    ("依赖", "Depends on"),
    ("基于", "Based on"),
    ("需要", "Need"),
    ("必须", "Must"),
    ("建议", "Recommended"),
    ("允许", "Allowed"),
    ("禁止", "Prohibited"),

    # ── Nouns / Concepts ──
    ("数据", "Data"),
    ("内存", "Memory"),
    ("缓存", "Buffer"),
    ("图像", "Image"),
    ("视频", "Video"),
    ("音频", "Audio"),
    ("通道", "Channel"),
    ("设备", "Device"),
    ("模块", "Module"),
    ("接口", "Interface"),
    ("参数", "Parameter"),
    ("属性", "Attribute"),
    ("功能", "Function"),
    ("模式", "Mode"),
    ("状态", "Status"),
    ("类型", "Type"),
    ("结构体", "Structure"),
    ("成员", "Member"),
    ("字段", "Field"),
    ("标志", "Flag"),
    ("标志位", "Flag"),
    ("句柄", "Handle"),
    ("指针", "Pointer"),
    ("地址", "Address"),
    ("偏移", "Offset"),
    ("大小", "Size"),
    ("宽度", "Width"),
    ("高度", "Height"),
    ("位置", "Position"),
    ("坐标", "Coordinate"),
    ("区域", "Region"),
    ("范围", "Range"),
    ("数量", "Count"),
    ("编号", "Number"),
    ("索引", "Index"),
    ("版本", "Version"),
    ("描述", "Description"),
    ("信息", "Information"),
    ("配置", "Configuration"),
    ("发送", "Sending"),
    ("接收", "Receiving"),
    ("处理", "Processing"),
    ("编码", "Encoding"),
    ("解码", "Decoding"),
    ("压缩", "Compression"),
    ("解压", "Decompression"),
    ("旋转", "Rotation"),
    ("缩放", "Scaling"),
    ("裁剪", "Cropping"),
    ("镜像", "Mirroring"),
    ("翻转", "Flipping"),
    ("拼接", "Splicing"),
    ("叠加", "Overlay"),
    ("校正", "Correction"),
    ("降噪", "Noise Reduction"),
    ("增强", "Enhancement"),
    ("畸变", "Distortion"),
    ("分辨率", "Resolution"),
    ("帧率", "Frame Rate"),
    ("码率", "Bitrate"),
    ("码流", "Bitstream"),
    ("寄存器", "Register"),
    ("硬件", "Hardware"),
    ("软件", "Software"),
    ("驱动", "Driver"),
    ("内核", "Kernel"),
    ("用户", "User"),
    ("应用", "Application"),
    ("系统", "System"),
    ("资源", "Resource"),
    ("线程", "Thread"),
    ("任务", "Task"),
    ("事件", "Event"),
    ("结果", "Result"),
    ("错误", "Error"),
    ("成功", "Success"),
    ("失败", "Failure"),
    ("超时", "Timeout"),

    # ── Common standalone words ──
    ("输入", "Input"),
    ("输出", "Output"),
    ("定义", "Definition"),
    ("协议", "Protocol"),
    ("章节", "Chapter"),
    ("具体", "Specific"),
    ("单位", "Unit"),
    ("物理", "Physical"),
    ("开启", "Enable"),
    ("控制", "Control"),
    ("参考", "Reference"),
    ("关闭", "Close"),
    ("启用", "Enable"),
    ("离线", "Offline"),
    ("目标", "Target"),
    ("指定", "Specified"),
    ("放大", "Zoom"),
    ("实际", "Actual"),
    ("保证", "Ensure"),
    ("起始", "Start"),
    ("色调", "Hue"),
    ("是否", "Whether"),
    ("图片", "Picture"),
    ("格式", "Format"),
    ("决定", "Determines"),
    ("限制", "Limit"),
    ("要求", "Requirement"),
    ("次数", "Times"),
    ("在线", "Online"),
    ("方式", "Method"),
    ("复合", "Composite"),
    ("鱼眼", "Fisheye"),
    ("生效", "Takes Effect"),
    ("率控制", "Rate Control"),
    ("最大值", "Maximum Value"),
    ("最小值", "Minimum Value"),
    ("大于", "Greater Than"),
    ("小于", "Less Than"),
    ("等于", "Equal To"),
    ("不等于", "Not Equal To"),
    ("预留", "Reserved"),
    ("暂不支持", "Not Yet Supported"),
    ("不支持", "Not Supported"),
    ("参见", "See"),
    ("须知", "Important"),
    ("默认", "Default"),
    ("时的", "When"),
    ("中的一个", ""),
    ("中的", "In"),
    ("本章", "This Chapter"),
    ("本节", "This Section"),
    ("上图", "Above Figure"),
    ("下图", "Below Figure"),
    ("如表", "As Shown In Table"),
    ("例如", "For Example"),
    ("其他", "Other"),
    ("其中", "Where"),
    ("该项", "This Item"),
    ("此值", "This Value"),
    ("两种", "Two Types"),
    ("三种", "Three Types"),
    ("后续", "Subsequent"),
    ("前述", "Aforementioned"),
    ("同理", "Similarly"),
    ("反之", "Conversely"),
    ("注意", "Note"),
    ("事项", "Items"),
    ("差值", "Difference"),
    ("特征", "Feature"),
    ("开始", "Start"),
    ("联扩展", "Linked Extension"),
    ("阻塞", "Blocking"),
    ("情况", "Situation"),
    ("自适", "Adaptive"),
    ("传输", "Transmission"),
    ("变量", "Variable"),
    ("边框", "Border"),
    ("恢复", "Recovery"),
    ("失效", "Invalidation"),
    ("重新", "Re-"),
    ("重复", "Repeat"),
    ("芯片", "Chip"),
    ("分别", "Respectively"),
    ("特殊", "Special"),
    ("模糊", "Blur"),
    ("配合", "Cooperate"),
    ("电平", "Level"),
    ("静止", "Static"),
    ("一致", "Consistent"),
    ("几何", "Geometry"),
    ("涉及", "Involves"),
    ("直方图", "Histogram"),
    ("增益", "Gain"),
    ("门限值", "Threshold"),
    ("标记", "Mark"),
    ("画面", "Picture"),
    ("刷新", "Refresh"),
    ("意义", "Meaning"),
    ("码控", "Rate Control"),
    ("清晰", "Clear"),
    ("不更改", "Unchanged"),
    ("上限", "Upper Limit"),
    ("存储", "Storage"),
    ("卷绕", "Winding"),
    ("丢弃", "Drop"),
    ("依次提", "Sequentially"),
    ("性越小", "Smaller"),
    ("最终都会被约束", "Eventually Constrained"),
    ("最强烈", "Strongest"),
    ("求下", "Requirement"),
    ("时才", "Only When"),
    ("上的", "On"),
    ("下的", "Under"),
    ("的值", "Value"),
    ("值增大", "Value Increases"),
    ("联扩展", "Link Extension"),
    ("差值", "Difference Value"),
    ("调用", "Call"),
    ("智能", "Smart"),
    ("设置", "Set"),
    ("图像", "Image"),
    ("属性", "Attribute"),
    ("长度", "Length"),
    ("用户", "User"),
    ("占用", "Occupied"),
    ("只能", "Can Only"),
    ("标准", "Standard"),
    ("分割", "Split"),
    ("抓拍", "Snapshot"),
    ("残留", "Residual"),
    ("调整", "Adjust"),
    ("枚举", "Enumeration"),
    ("超出", "Exceeds"),
    ("复用", "Multiplex"),
    ("记录", "Record"),
    ("高度", "Height"),
    ("获取", "Get"),
    ("才能", "Can Only"),
    ("运动", "Motion"),
    ("强度", "Intensity"),
    ("手动", "Manual"),
    ("超大", "Super Large"),
    ("代表", "Represents"),
    ("钳位", "Clamp"),
    ("瞬时", "Instantaneous"),
    ("上下文", "Context"),
    ("算法", "Algorithm"),
    ("客户", "Customer"),
    ("前景", "Foreground"),
    ("量化", "Quantization"),
    ("多个", "Multiple"),
    ("处于", "In"),
    ("异常", "Abnormal"),
    ("策略", "Strategy"),
    ("呼吸效", "Breathing Effect"),
    ("的熵", "Entropy"),
    ("的含义", "Meaning"),
    ("倍缩小", "Times Reduction"),
    ("模式下", "In Mode"),
    ("值的", "Value"),
    ("越多", "More"),
    ("设备接口未", "Device Interface Not"),
    ("下一个", "Next"),
    ("下一", "Next"),
    ("超大", "Oversized"),
    ("只能", "Only"),
    ("获取", "Retrieve"),
    ("效果", "Effect"),
    ("显示", "Display"),
    ("禁用", "Disable"),
    ("动态", "Dynamic"),
    ("场景", "Scenario"),
    ("时间", "Time"),
    ("量化表", "Quantization Table"),
    ("时序", "Timing"),
    ("内部", "Internal"),
    ("紧凑段", "Compact Segment"),
    ("亮度", "Luminance"),
    ("马赛克", "Mosaic"),
    ("质量", "Quality"),
    ("检测", "Detection"),
    ("打开", "Open"),
    ("释放", "Release"),
    ("计数", "Count"),
    ("数目", "Number"),
    ("垂直", "Vertical"),
    ("后端", "Backend"),
    ("调节", "Adjust"),
    ("优先", "Priority"),
    ("镜头", "Lens"),
    ("插入", "Insert"),
    ("变换", "Transform"),
    ("改变", "Change"),
    ("阈值", "Threshold"),
    ("提交", "Submit"),
    ("宽高", "Width/Height"),
    ("变动", "Change"),
    ("影响", "Affect"),
    ("操作", "Operation"),
    ("排布", "Layout"),
    ("关系", "Relationship"),
    ("公共", "Public"),
    ("自动", "Automatic"),
    ("矩阵", "Matrix"),
    ("会导致", "May Cause"),
    ("过程中被", "During"),
    ("的倾", "Tilt"),
    ("情况下", "In Case"),
    ("不能", "Cannot"),
    ("不同的", "Different"),
    ("后的", "After"),
    ("的最大", "Maximum"),
    ("的最小", "Minimum"),
    ("静态", "Static"),
    ("前端", "Frontend"),
    ("频率", "Frequency"),
    ("分频", "Division"),
    ("信号", "Signal"),
    ("同步", "Sync"),
    ("水平", "Horizontal"),
    ("统计", "Statistics"),
    ("编码器", "Encoder"),
    ("解码器", "Decoder"),
    ("调节器", "Regulator"),
    ("处理器", "Processor"),
    ("控制器", "Controller"),
    ("检测器", "Detector"),
    ("发生器", "Generator"),
    ("缓存区", "Buffer Area"),
    ("缓冲区", "Buffer"),
    ("内存池", "Memory Pool"),
    ("分配池", "Allocation Pool"),
    ("像素点", "Pixel"),
    ("当前帧", "Current Frame"),
    ("参考帧", "Reference Frame"),
    ("编码帧", "Encoded Frame"),
    ("解码帧", "Decoded Frame"),
    ("关键帧", "Key Frame"),
    ("I 帧", "I Frame"),
    ("P 帧", "P Frame"),
    ("B 帧", "B Frame"),

    # ── Connectives ──
    ("之后", "After"),
    ("之前", "Before"),
    ("之内", "Within"),
    ("之外", "Outside"),
    ("之间", "Between"),
    ("以及", "And"),
    ("或者", "Or"),
    ("但是", "But"),
    ("因此", "Therefore"),
    ("所以", "So"),
    ("因为", "Because"),
    ("如果", "If"),
    ("否则", "Otherwise"),
    ("此时", "At this time"),
    ("同时", "Simultaneously"),
    ("另外", "Additionally"),
    ("例如", "For example"),
    ("比如", "Such as"),
    ("包括", "Including"),
    ("包含", "Containing"),
    ("除了", "Except"),
    ("只要", "As long as"),
    ("只有", "Only if"),
    ("无论", "Regardless"),
    ("尽管", "Although"),
    ("即使", "Even if"),
    ("除非", "Unless"),
    ("直到", "Until"),
    ("按照", "According to"),
    ("根据", "Based on"),
    ("通过", "Through"),
    ("利用", "Using"),
    ("采用", "Adopting"),
    ("针对", "For"),
    ("关于", "Regarding"),
    ("由于", "Due to"),
    ("随着", "As"),
    ("接着", "Then"),
    ("首先", "First"),
    ("其次", "Second"),
    ("最后", "Finally"),
    ("然后", "Then"),
    ("接下来", "Next"),
    ("进一步", "Further"),
    ("特别", "Especially"),
    ("尤其", "Particularly"),
    ("主要", "Mainly"),
    ("通常", "Usually"),
    ("一般", "Generally"),
    ("可能", "Possibly"),
    ("一定", "Definitely"),

    # ── Quantifiers ──
    ("所有", "All"),
    ("每个", "Each"),
    ("整个", "Entire"),
    ("部分", "Partial"),
    ("若干", "Several"),
    ("一些", "Some"),
    ("许多", "Many"),
    ("大量", "Large amount"),
    ("少量", "Small amount"),
    ("足够", "Enough"),
    ("不足", "Insufficient"),
    ("超过", "Exceeds"),
    ("至少", "At least"),
    ("至多", "At most"),
    ("大约", "Approximately"),
    ("精确", "Precise"),
    ("总共", "Total"),
    ("平均", "Average"),
    ("最高", "Maximum"),
    ("最低", "Minimum"),
    ("最佳", "Optimal"),
    ("更大", "Larger"),
    ("更小", "Smaller"),
    ("更长", "Longer"),
    ("更短", "Shorter"),

    # ── Time ──
    ("立即", "Immediately"),
    ("延迟", "Delay"),
    ("提前", "In advance"),
    ("实时", "Real-time"),
    ("定时", "Timed"),
    ("周期", "Period"),
    ("间隔", "Interval"),
    ("持续", "Continuous"),
    ("逐渐", "Gradually"),
    ("始终", "Always"),
    ("已经", "Already"),
    ("正在", "Currently"),
    ("暂时", "Temporarily"),
    ("永久", "Permanently"),
]

PASS_3 = [
    # ── Single-character / short remnants ──
    ("并", "And"),
    ("与", "And"),
    ("或", "Or"),
    ("且", "And"),
    ("但", "But"),
    ("可", "Can"),
    ("应", "Should"),
    ("需", "Need"),
    ("若", "If"),
    ("则", "Then"),
    ("如", "Such as"),
    ("无", "No"),
    ("有", "Has"),
    ("是", "Is"),
    ("否", "No"),
    ("仅", "Only"),
    ("均", "All"),
    ("已", "Already"),
    ("未", "Not"),
    ("非", "Non-"),
    ("即", "i.e."),
    ("等", "etc."),
    ("每", "Per"),
    ("该", "The"),
    ("此", "This"),
    ("其", "Its"),
    ("所", "That which"),
    ("之", "Of"),
    ("以", "By"),
    ("于", "At"),
    ("对", "To"),
    ("从", "From"),
    ("向", "Toward"),
    ("到", "To"),
    ("使", "Make"),
    ("令", "Make"),
    ("设", "Set"),
    ("取", "Get"),
    ("加", "Add"),
    ("减", "Subtract"),
    ("乘", "Multiply"),
    ("除", "Divide"),
    ("比", "Compare"),
    ("按", "Press"),
    ("点", "Point"),
    ("行", "Row"),
    ("列", "Column"),
    ("层", "Layer"),
    ("帧", "Frame"),
    ("包", "Packet"),
    ("块", "Block"),
    ("路", "Path"),
    ("组", "Group"),
    ("级", "Level"),
]

PASS_4 = [
    # ── Compounds first (before single chars) ──
    ("不会", "will not"),
    ("不能", "cannot"),
    ("不可", "cannot"),
    ("只有", "only"),
    ("只要", "as long as"),
    ("才能", "can"),
    ("只能", "only"),
    ("都可", "all can"),
    ("也可", "can also"),
    ("并不", "does not"),
    ("不再", "no longer"),
    ("不仅", "not only"),
    ("不够", "insufficient"),
    ("不一定", "not necessarily"),
    ("的一样", "same"),
    ("的时候", "when"),
    ("的情况下", "when"),
    ("过程中", "during"),
    ("平滑过渡", "smooth transition"),
    ("非平滑过渡", "non-smooth transition"),
    ("此场景", "this scenario"),
    ("此接口", "this interface"),
    ("此功能", "this function"),
    ("此模式", "this mode"),
    ("此参数", "this parameter"),
    ("此值", "this value"),
    ("此时", "at this time"),
    ("上报", "report"),
    ("报错", "error"),
    ("会报错", "will error"),
    ("可能会", "may"),
    ("优先级", "priority"),
    ("数值越", "value"),
    ("纯色模式", "solid color mode"),
    ("分配", "allocate"),
    ("虚拟", "virtual"),
    ("每个", "each"),
    ("最多", "at most"),
    ("至少", "at least"),
    ("扩展通道", "extension channel"),
    ("绑定源", "binding source"),
    ("必须为", "must be"),
    ("宏块", "macroblock"),
    ("采用", "using"),
    ("启用", "enable"),
    ("禁用", "disable"),
    ("挂死", "hang"),
    ("插值", "interpolation"),
    ("小端字节序", "little-endian byte order"),
    ("噪声", "noise"),
    ("桶型校正", "barrel correction"),
    ("拉伸", "stretch"),
    ("获得较好", "obtain better"),
    ("稳定效果", "stabilization effect"),
    ("降低", "reduce"),
    ("延时", "latency"),
    ("此配置", "this configuration"),
    ("可能导致", "may cause"),
    ("色度", "chroma"),
    ("消隐区", "blanking area"),
    ("倒数第", "countdown"),
    ("逐行", "progressive"),
    ("对齐", "alignment"),
    ("花屏", "screen corruption"),
    ("绘制", "rendering"),
    ("提交", "submit"),
    ("发生", "occur"),
    ("原因", "reason"),
    ("返回错误码", "returns error code"),
    ("目标帧率", "target frame rate"),
    ("用户图像帧率", "user image frame rate"),
    ("静态帧率", "static frame rate"),
    ("动态帧率", "dynamic frame rate"),
    ("帧率控制", "frame rate control"),
    ("码率控制", "rate control"),
    ("固定码率", "constant bitrate"),
    ("可变码率", "variable bitrate"),
    ("平均码率", "average bitrate"),
    ("最大码率", "maximum bitrate"),
    ("量化参数", "quantization parameter"),
    ("图像质量", "image quality"),
    ("编码效率", "encoding efficiency"),
    ("压缩比", "compression ratio"),
    ("去噪", "denoising"),
    ("锐化", "sharpening"),
    ("对比度", "contrast"),
    ("饱和度", "saturation"),
    ("色相", "hue"),
    ("伽马", "gamma"),
    ("白平衡", "white balance"),
    ("自动曝光", "auto exposure"),
    ("自动对焦", "auto focus"),
    ("自动白平衡", "auto white balance"),
    ("数字变焦", "digital zoom"),
    ("光学变焦", "optical zoom"),
    ("电子防抖", "electronic image stabilization"),
    ("光学防抖", "optical image stabilization"),
    ("宽动态范围", "wide dynamic range"),
    ("高动态范围", "high dynamic range"),
    ("背光补偿", "backlight compensation"),
    ("强光抑制", "highlight suppression"),
    ("透雾", "defog"),
    ("走廊模式", "corridor mode"),
    ("感兴趣区域", "region of interest"),
    ("隐私遮挡", "privacy mask"),
    ("运动检测", "motion detection"),
    ("遮挡报警", "tampering alarm"),
    ("视频诊断", "video diagnostics"),
    ("智能分析", "intelligent analysis"),
    ("人脸检测", "face detection"),
    ("车牌识别", "license plate recognition"),
    ("音频编解码", "audio codec"),
    ("回声消除", "echo cancellation"),
    ("降噪处理", "noise reduction processing"),
    ("语音增强", "voice enhancement"),
    ("声源定位", "sound source localization"),
    ("语音识别", "speech recognition"),
    ("语音合成", "speech synthesis"),
    # ── Single chars ──
    ("的了", ""),
    ("在了", ""),
    ("的", ""),
    ("了", ""),
    ("在", ""),
    ("是", ""),
    ("中", ""),
    ("个", ""),
    ("和", "and"),
    ("被", "by"),
    ("把", ""),
    ("对", ""),
    ("从", "from"),
    ("到", "to"),
    ("与", "and"),
    ("及", "and"),
    ("时", "when"),
    ("值", "value"),
    ("不", "not"),
    ("数", "number"),
    ("度", ""),
    ("率", "rate"),
    ("会", "will"),
    ("下", "under"),
    ("一", "one"),
    ("相", ""),
    ("后", "after"),
    ("越", ""),
    ("大", "large"),
    ("分", ""),
    ("上", "on"),
    ("前", "before"),
    ("源", "source"),
    ("宏", "macro"),
    ("去", ""),
    ("小", "small"),
    ("声", "sound"),
    ("定", ""),
    ("较", "relatively"),
    ("低", "low"),
    ("这", "this"),
    ("噪", "noise"),
    ("联", ""),
    ("例", "example"),
    ("只", "only"),
    ("将", "will"),
    ("本", "this"),
    ("当", "when"),
    ("需", "need"),
    ("可", "can"),
    ("应", "should"),
    ("该", "the"),
    ("均", "all"),
    ("即", "i.e."),
    ("或", "or"),
    ("无", "no"),
    ("有", "have"),
    ("没", "not"),
    ("未", "not yet"),
    ("非", "non-"),
    ("已", "already"),
    ("仍", "still"),
    ("再", "again"),
    ("最", "most"),
    ("更", "more"),
    ("很", "very"),
    ("都", "all"),
    ("也", "also"),
    ("就", "then"),
    ("才", "only then"),
    ("还", "still"),
    ("要", "need"),
    ("能", "can"),
    ("可能", "may"),
    ("必须", "must"),
    ("一定", "must"),
    ("通过", "via"),
    ("因此", "therefore"),
    ("因为", "because"),
    ("所以", "therefore"),
    ("然后", "then"),
    ("但是", "but"),
    ("如果", "if"),
    ("虽然", "although"),
    ("即使", "even if"),
    ("除非", "unless"),
    ("除了", "except"),
    ("按照", "according to"),
    ("根据", "based on"),
    ("由于", "due to"),
    ("为了", "in order to"),
    ("关于", "regarding"),
    ("对于", "for"),
    ("随着", "as"),
    ("经过", "after"),
    ("包括", "including"),
    ("包含", "containing"),
    ("排除", "excluding"),
    ("选择", "select"),
    ("取消", "cancel"),
    ("确认", "confirm"),
    ("添加", "add"),
    ("移除", "remove"),
    ("修改", "modify"),
    ("创建", "create"),
    ("销毁", "destroy"),
    ("初始化", "initialize"),
    ("释放", "release"),
    ("申请", "request"),
    ("拷贝", "copy"),
    ("移动", "move"),
    ("查找", "find"),
    ("遍历", "traverse"),
    ("插入", "insert"),
    ("排序", "sort"),
    ("比较", "compare"),
    ("交换", "swap"),
    ("触发", "trigger"),
    ("响应", "respond"),
    ("处理", "process"),
    ("等待", "wait"),
    ("唤醒", "wake"),
    ("睡眠", "sleep"),
    ("超时", "timeout"),
    ("重试", "retry"),
    ("回滚", "rollback"),
    ("提交", "commit"),
    ("保存", "save"),
    ("加载", "load"),
    ("解析", "parse"),
    ("序列化", "serialize"),
    ("反序列化", "deserialize"),
    ("编码", "encode"),
    ("解码", "decode"),
    ("加密", "encrypt"),
    ("解密", "decrypt"),
    ("压缩", "compress"),
    ("解压", "decompress"),
    ("校验", "verify"),
    ("签名", "sign"),
    ("认证", "authenticate"),
    ("授权", "authorize"),
    ("登录", "login"),
    ("登出", "logout"),
    ("注册", "register"),
    ("注销", "unregister"),
    ("订阅", "subscribe"),
    ("发布", "publish"),
    ("广播", "broadcast"),
    ("组播", "multicast"),
    ("单播", "unicast"),
    # catch-all: any remaining Chinese char → ""
    ("该", "the"),
    ("其", "its"),
    ("此", "this"),
    ("所", ""),
    ("向", "to"),
    ("用", "use"),
    ("做", "do"),
    ("让", "let"),
    ("给", "give"),
    ("来", "to"),
    ("进", "enter"),
    ("出", "exit"),
    ("回", "return"),
    ("开", "open"),
    ("关", "close"),
    ("使", "enable"),
    ("停", "stop"),
    ("起", "start"),
    ("高", "high"),
    ("多", "many"),
    ("少", "few"),
    ("新", "new"),
    ("旧", "old"),
    ("长", "long"),
    ("短", "short"),
    ("快", "fast"),
    ("慢", "slow"),
    ("好", "good"),
    ("坏", "bad"),
    ("真", "true"),
    ("假", "false"),
    ("空", "empty"),
    ("满", "full"),
    ("正", "positive"),
    ("负", "negative"),
    ("左", "left"),
    ("右", "right"),
    ("内", "inside"),
    ("外", "outside"),
    ("远", "far"),
    ("近", "near"),
    ("深", "deep"),
    ("浅", "shallow"),
    ("宽", "wide"),
    ("窄", "narrow"),
    ("厚", "thick"),
    ("薄", "thin"),
    ("硬", "hard"),
    ("软", "soft"),
    ("强", "strong"),
    ("弱", "weak"),
    ("亮", "bright"),
    ("暗", "dark"),
    ("热", "hot"),
    ("冷", "cold"),
    ("干", "dry"),
    ("湿", "wet"),
    ("轻", "light"),
    ("重", "heavy"),
    ("早", "early"),
    ("晚", "late"),
    ("先", "first"),
    ("双", "dual"),
    ("单", "single"),
    ("全", "full"),
    ("半", "half"),
    ("同", "same"),
    ("异", "different"),
    ("等", "etc."),
    ("类", "type"),
    ("种", "kind"),
    ("组", "group"),
    ("套", "set"),
    ("块", "block"),
    ("段", "segment"),
    ("行", "row"),
    ("帧", "frame"),
    ("场", "field"),
    ("包", "packet"),
    ("流", "stream"),
    ("路", "path"),
    ("层", "layer"),
    ("级", "level"),
    ("步", "step"),
    ("轮", "round"),
    # ── Critical cleanup for readability ──
    ("沿", "edge"),
    ("屏", "screen"),
    ("制式", "format"),
    ("固", "fixed"),
    ("各", "each"),
    ("身", ""),
    ("备", ""),
    ("具", "has"),
    ("终", "final"),
    ("三", "three"),
    ("看", "seen"),
    ("出", "out"),
    ("画", "draw"),
    ("布", "canvas"),
    ("那", "then"),
    ("适", "suitable"),
    ("理", "arrange"),
    ("合", "combine"),
    ("右", "right"),
    ("角", "corner"),
    ("倍", "times"),
    ("节", "save"),
    ("过", ""),
    ("望", "hope"),
    ("力", "capability"),
    ("容", "content"),
    ("原", "origin"),
    ("烁", "flicker"),
    ("满", "satisfy"),
    ("足", ""),
    ("充", "fill"),
    ("示", "shown"),
    ("别", "note"),
    ("截", "capture"),
    ("交", "intersection"),
    ("部", "part"),
    ("清", "clear"),
    ("偶", "even"),
    ("邻", "adjacent"),
    ("两", "two"),
    ("变", "change"),
    ("捕", "capture"),
    ("区", "distinguish"),
    ("主", "main"),
    ("函", "function"),
    ("态", "state"),
    ("钩", "hook"),
    ("子", "child"),
    ("丝", "wire"),
    ("焊", "solder"),
    ("盘", "pad"),
    ("贴", "attach"),
    ("片", "chip"),
    ("封", "package"),
    ("装", "assembly"),
    ("裸", "bare"),
    ("模", "module"),
    ("拟", "analog"),
    ("仪", "instrument"),
    ("表", "meter"),
    ("载", "load"),
    ("存", "store"),
    ("取", "fetch"),
    ("返", "return"),
    ("调", "adjust"),
    ("试", "test"),
    ("测", "measure"),
    ("判", "judge"),
    ("断", "determine"),
    ("循", "loop"),
    ("环", "ring"),
    ("递", "recursion"),
    ("归", "reduction"),
    ("排", "arrange"),
    ("序", "order"),
    ("搜", "search"),
    ("索", "search"),
    ("索", "search"),
    ("跳", "jump"),
    ("转", "transfer"),
    ("派", "dispatch"),
    ("异", "exception"),
    ("掉", "drop"),
    ("丢", "lose"),
    ("重", "re-"),
    ("漏", "leak"),
    ("溢", "overflow"),
    ("崩", "crash"),
    ("溃", "collapse"),
    ("卡", "stuck"),
    ("顿", "stutter"),
    ("延", "delay"),
    ("抖", "jitter"),
    ("闪", "flash"),
    ("花", "garbled"),
    ("绿", "green"),
    ("红", "red"),
    ("蓝", "blue"),
    ("黑", "black"),
    ("白", "white"),
    ("灰", "gray"),
    ("彩", "color"),
    ("透", "transparent"),
    ("镜", "mirror"),
    ("窗", "window"),
    ("门", "gate"),
    ("锁", "lock"),
    ("钥", "key"),
    ("签", "tag"),
    ("标", "mark"),
    ("针", "pointer"),
    ("引", "index"),
    ("栈", "stack"),
    ("队", "queue"),
    ("树", "tree"),
    ("图", "graph"),
    ("链", "chain"),
    ("表", "list"),
    ("散", "hash"),
    ("堆", "heap"),
    ("池", "pool"),
    ("域", "domain"),
    ("界", "boundary"),
    ("限", "limit"),
    ("障", "barrier"),
    ("栅", "fence"),
    ("屏", "screen"),
    ("幕", "screen"),
    ("显", "display"),
    ("隐", "hidden"),
    ("藏", "hide"),
    ("秘", "secret"),
    ("密", "dense"),
    ("安", "security"),
    ("防", "guard"),
    ("护", "protect"),
    ("检", "check"),
    ("校", "calibrate"),
    ("验", "verify"),
    ("错", "error"),
    ("警", "alarm"),
    ("告", "warning"),
    ("提", "prompt"),
    ("询", "query"),
    ("答", "answer"),
    ("问", "question"),
    ("帮", "help"),
    ("助", "assist"),
]

MISSING_PHRASES = [
    ("平稳", "steady"),
    ("投影", "projection"),
    ("平稳性", "stability"),
    ("平衡", "balance"),
    ("视频输出", "Video Output"),
    ("视频编码", "Video Encoding"),
    ("厂商", "vendor"),
    ("方形", "square"),
    ("云台", "gimbal"),
    ("产品", "product"),
    ("牺牲", "sacrifice"),
    ("剧烈", "drastic"),
    ("音乐", "music"),
    ("音轨", "audio track"),
    ("优化", "optimization"),
    ("水印", "watermark"),
    ("简化", "simplify"),
    ("手持", "handheld"),
    ("航拍", "aerial photography"),
    ("意味着", "means"),
    ("指导", "guidance"),
    ("构建", "build"),
    ("完成", "completion"),
    ("完毕", "complete"),
    ("混淆", "confusion"),
    ("补偿", "compensation"),
    ("请勿", "do not"),
    ("条纹", "stripe"),
    ("详见", "see details in"),
    ("残影", "residual image"),
    ("锯齿", "aliasing"),
    ("形式", "form"),
    ("紧凑型", "compact"),
    ("确切", "exact"),
    ("预测", "prediction"),
    ("耗费", "cost"),
    ("陆续", "successively"),
    ("名字", "name"),
    ("剪裁", "clip"),
    ("他们", "they"),
    ("指哪", "which kind"),
    ("待", "to-be-"),
    ("横", "horizontal"),
    ("纵", "vertical"),
    ("决", "determined"),
    ("集", "intersection"),
    ("管", "manage"),
    ("局", "layout"),
    ("意", "meaning"),
    ("积", "area"),
    ("自", "self-"),
    ("请自", "please"),
    ("涵盖住", "cover"),
    ("麦平滑信", "microphone smoothing signal"),
]

# ── All passes in order ──
ALL_PASSES = [MISSING_PHRASES, PASS_1, PASS_2, PASS_3, PASS_4]
