#!/usr/bin/env python3
"""Translate Chinese proc debug documentation to English."""

import re

def translate_text(text):
    """Translate Chinese text to English, preserving non-translatable elements."""
    if not text:
        return text

    # Translation dictionary for common Chinese technical terms
    translations = {
        # Section headings
        '【调试信息】': '[Debug Info]',
        '【调试信息分析】': '[Debug Info Analysis]',
        '【参数说明】': '[Parameter Description]',
        '【调试信息说明】': '[Debug Info Description]',

        # Table header
        '参数': 'Parameter',
        '描述': 'Description',

        # Common descriptions
        'Grp ID号。': 'Grp ID number.',
        '有效范围：': 'Valid range: ',
        '单位：像素': 'Unit: pixel',
        '以像素为单位': 'in pixels',
        '使能': 'Enable',
        '使能。': 'Enable.',
        '使能：': 'Enable: ',
        '使能状态': 'Enable status',
        '是否使能': 'Whether to enable',
        '是否使能CROP功能。': 'Whether to enable the CROP function.',
        '是否使能LDCI功能。': 'Whether to enable the LDCI function.',
        '是否使能mirror功能。': 'Whether to enable the mirror function.',
        '是否使能flip功能。': 'Whether to enable the flip function.',
        '是否使能扩展通道。': 'Whether to enable the extended channel.',
        '是否使能提前发送功能。': 'Whether to enable early send function.',
        '是否开始接收图像。': 'Whether to start receiving images.',
        '是否保持幅形比。': 'Whether to maintain aspect ratio.',
        '是否使用用户设置的鱼眼镜头LMF参数。': 'Whether to use user-set fisheye lens LMF parameters.',
        'Y：使能；': 'Y: Enable;',
        'N：使能。': 'N: Enable.',
        'N：不使能。': 'N: Disable.',
        'Y：不使能。': 'Y: Disable.',
        'Y：使能。': 'Y: Enable.',
        'N：不使能；': 'N: Disable;',
        'Y：打开；': 'Y: On;',
        'Y：打开。': 'Y: On.',
        'N：关闭；': 'N: Off;',
        'N：关闭。': 'N: Off.',
        'N：关闭': 'N: Off',
        'Y：打开': 'Y: On',
        'N：不使能': 'N: Disable',
        'Y：使能': 'Y: Enable',
        'Y：支持。': 'Y: Supported.',
        'N：不支持。': 'N: Not supported.',
        'Y：支持': 'Y: Supported',
        'N：不支持': 'N: Not supported',
        '0：不使能；': '0: Disable;',
        '1：使能。': '1: Enable.',
        '0：不使用；': '0: Not used;',
        '1：使用。': '1: Used.',
        '0：不使能': '0: Disable',
        '1：使能': '1: Enable',
        '0：关闭；': '0: Off;',
        '1：打开。': '1: On.',
        '0：静音数据；': '0: Mute data;',
        '1：非静音数据。': '1: Non-mute data.',
        'NULL：未占用；': 'NULL: Not occupied;',
        '1：占用。': '1: Occupied.',
        'NULL：未占用；': 'NULL: Not occupied;',
        '1：占用。': '1: Occupied.',
        'N：关闭': 'N: Off',
        'Y：打开': 'Y: On',

        # Parameters that need context-specific translation
        '分块节点数量。取值范围为[1,16]，默认值为3，通过模块参数接口修改。': 'Number of split node. Valid range: [1,16], default value: 3, modified through the module parameter interface.',
        '是否支持Coverex相对坐标。': 'Whether to support Coverex relative coordinates.',
        '调度模式，通过SYS接口设置。': 'Scheduling mode, set through the SYS interface.',
        'NORMAL：正常调度模式。': 'NORMAL: Normal scheduling mode.',
        'QUICK：快速调度模式。': 'QUICK: Quick scheduling mode.',
        '3DNR延时模式使能。': '3DNR delay mode enable.',
        '组的多任务使能。': 'Group multi-task enable.',
        'VPSS模块高性开关，仅Hi3403V100支持。': 'VPSS module high performance switch, only supported by Hi3403V100.',
        'N：不使能；': 'N: Disable;',
        'VPSS组链阈值。': 'VPSS group chain threshold.',
        '有效范围：[40, 160]。': 'Valid range: [40, 160].',
        'VPSS支持输出低延时开关。': 'VPSS supports output low delay switch.',
        'VPSS proc统计处理时间数据开关。': 'VPSS proc statistics processing time data switch.',
        '关闭时VPSS proc中的cost_time、max_cost_time、proc_time、中断工作时间等信息不进行统计。': 'When disabled, cost_time, max_cost_time, proc_time, interrupt work time and other information in VPSS proc are not counted.',
        'VPSS组参数及配置信息': 'VPSS group parameters and configuration info',
        'DCI强度。': 'DCI intensity.',
        'IE强度。': 'IE intensity.',
        '是否开启尺寸筛选。': 'Whether to enable size filter.',
        '筛选尺寸宽。': 'Filter size width.',
        '筛选尺寸高。': 'Filter size height.',
        '组Mosaic数量。': 'Number of group Mosaic.',
        '组Cover数量。': 'Number of group Cover.',
        '组OSD数量。': 'Number of group OSD.',
        '最后一次提交给组的亮度和任务数。': 'Last submitted group luminance and task count.',
        '坐标类型。': 'Coordinate type.',
        'RAT：相对坐标；': 'RAT: Relative coordinate;',
        'ABS：绝对坐标。': 'ABS: Absolute coordinate.',
        'ABS：绝对坐标': 'ABS: Absolute coordinate',
        '水平方向起始坐标。': 'Horizontal start coordinate.',
        '垂直方向起始坐标。': 'Vertical start coordinate.',
        '实际图像起始点坐标。': 'Actual image start point coordinate.',
        '实际图像起始点x坐标。': 'Actual image start point x coordinate.',
        '实际图像起始点y坐标。': 'Actual image start point y coordinate.',
        '实际图像宽。': 'Actual image width.',
        '实际图像高。': 'Actual image height.',
        'CROP RECT的宽度，不能超出最大图像宽度。': 'Width of CROP RECT, cannot exceed the maximum image width.',
        'CROP RECT的高度，不能超出最大图像高度。': 'Height of CROP RECT, cannot exceed the maximum image height.',
        'CROP RECT的宽，不能超出最大图像宽度。': 'Width of CROP RECT, cannot exceed the maximum image width.',
        'CROP RECT的高，不能超出最大图像高度。': 'Height of CROP RECT, cannot exceed the maximum image height.',
        'VPSS 3DNR V1版本标准参数': 'VPSS 3DNR V1 standard parameters',
        '3DNR标准参数版本': '3DNR standard parameter version',
        'VER_1：版本1；': 'VER_1: Version 1;',
        'VER_2：版本2。': 'VER_2: Version 2.',
        '亮度空域去噪强度（标准参数）': 'Luma spatial denoising strength (standard parameter)',
        '亮度时域去噪强度（标准参数）': 'Luma temporal denoising strength (standard parameter)',
        '色度空域去噪强度（标准参数）': 'Chroma spatial denoising strength (standard parameter)',
        '色度时域去噪强度（标准参数）': 'Chroma temporal denoising strength (standard parameter)',
        '处理输入时产生亮串色现象的能力强度（标准参数）': 'Brightness cross-color artifact suppression strength during input processing (standard parameter)',
        'VPSS 3DNR V2版本标准参数': 'VPSS 3DNR V2 standard parameters',
        '3DNR工作模式。': '3DNR working mode.',
        'ISO值。': 'ISO value.',
        '3DNR第0级时域开关。': '3DNR level 0 temporal switch.',
        '3DNR第1级时域开关，一般不建议调试，建议保持为默认值1。': '3DNR level 1 temporal switch. It is generally not recommended to adjust; keep the default value 1.',
        '4级亮度滤波器使能标识。': '4-level luma filter enable flag.',
        '0：当前滤波器不使能；': '0: Current filter disabled;',
        '1：当前滤波器使能。': '1: Current filter enabled.',
        '2级色度滤波器使能标识。': '2-level chroma filter enable flag.',
        'Limit range模式开关。': 'Limit range mode switch.',
        '空域滤波强度。': 'Spatial filter strength.',
        '调节色度的时滤波器参数。': 'Adjust chroma temporal filter parameters.',
        '调节第0级的空域滤波器参数。': 'Adjust level 0 spatial filter parameters.',
        '调节第0级的时域滤波器参数。': 'Adjust level 0 temporal filter parameters.',
        '调节第1级的空域滤波器参数。': 'Adjust level 1 spatial filter parameters.',
        '调节第1级的时域滤波器参数。': 'Adjust level 1 temporal filter parameters.',
        '调节第2级的空域滤波器参数。': 'Adjust level 2 spatial filter parameters.',
        '调节第2级的时域滤波器参数。': 'Adjust level 2 temporal filter parameters.',
        '调节第3级的空域滤波器参数。': 'Adjust level 3 spatial filter parameters.',
        '调节色度第1级的空域参数。': 'Adjust chroma level 1 spatial parameters.',
        'VPSS 3DNR高级参数': 'VPSS 3DNR advanced parameters',
        '区域运动阈值（高级参数）': 'Region motion threshold (advanced parameter)',
        '强去噪通道时域空域混合比重（高级参数）': 'Strong denoising channel temporal-spatial blend ratio (advanced parameter)',
        '区域强边缘阈值（高级参数）': 'Region strong edge threshold (advanced parameter)',
        '弱去噪通道时域空域混合比重（高级参数）': 'Weak denoising channel temporal-spatial blend ratio (advanced parameter)',
        '通道裁剪信息': 'Channel crop info',
        '通道ID号。': 'Channel ID number.',
        '用户做帧率控制。': 'User frame rate control.',
        'backup使能状态。在最开始没有帧输入时显示为N，有帧时会根据实际情况显示。': 'Backup enable status. Displays N when no frame input initially, and displays according to actual conditions when frames are available.',
        '3DNR使能。': '3DNR enable.',
        '3DNR模式。': '3DNR mode.',
        'VIDEO：视频模式；': 'VIDEO: Video mode;',
        'SNAP：拍照模式。': 'SNAP: Snapshot mode.',
        'VIDEO_SPA：视频纯空域模式。': 'VIDEO_SPA: Video pure spatial mode.',
        '参考帧压缩模式。': 'Reference frame compression mode.',
        'Y：压缩；': 'Y: Compressed;',
        'N：非压缩。': 'N: Uncompressed.',
        '3DNR运动矢量。': '3DNR motion vector.',
        'NORM：普通模式；': 'NORM: Normal mode;',
        'COMPENSATION：运动补偿模式。': 'COMPENSATION: Motion compensation mode.',
        '用户设置的输入输出Buffer复用状态。': 'User-set input/output buffer sharing status.',
        '实际生效的输入输出Buffer复用状态。': 'Actual effective input/output buffer sharing status.',
        'X：复用通道号，有效范围：[0, OT_VPSS_MAX_PHYS_CHN_NUM)': 'X: Shared channel number, valid range: [0, OT_VPSS_MAX_PHYS_CHN_NUM)',
        'N：关闭。': 'N: Off.',
        '用户设置的输入输出Buffer复用通道号。': 'User-set input/output buffer sharing channel number.',
        '有效范围：[0, OT_VPSS_MAX_PHYS_CHN_NUM)': 'Valid range: [0, OT_VPSS_MAX_PHYS_CHN_NUM)',
        'DCI使能状态': 'DCI enable status',
        'IE使能状态。': 'IE enable status.',
        'DEI模式。': 'DEI mode.',
        'OFF：强制关闭；': 'OFF: Force off;',
        'ON：强制打开；': 'ON: Force on;',
        'AUTO：自适应。': 'AUTO: Adaptive.',
        'DEI最大处理宽度。': 'DEI maximum processing width.',
        '有效范围：[64, OT_VPSS_MAX_DEI_HEIGHT]': 'Valid range: [64, OT_VPSS_MAX_DEI_HEIGHT]',
        'DEI最大处理高度。': 'DEI maximum processing height.',
        '有效范围：[64, OT_VPSS_MAX_IMG_HEIGHT]': 'Valid range: [64, OT_VPSS_MAX_IMG_HEIGHT]',
        'MCF使能。': 'MCF enable.',
        'Y：开启；': 'Y: On;',
        'Y：开启。': 'Y: On.',
        '幅形比模式。': 'Aspect ratio mode.',
        'NONE：关闭幅形比': 'NONE: Aspect ratio off',
        'AUTO：自动模式': 'AUTO: Auto mode',
        'MANUAL：手动模式': 'MANUAL: Manual mode',
        '视频位置X坐标。手动模式有效。': 'Video position X coordinate. Only valid in manual mode.',
        '视频位置Y坐标。手动模式有效。': 'Video position Y coordinate. Only valid in manual mode.',
        '视频宽度。手动模式有效。': 'Video width. Only valid in manual mode.',
        '视频高度。手动模式有效。': 'Video height. Only valid in manual mode.',
        '幅形比背景色。': 'Aspect ratio background color.',
        '有效范围：[0x0, 0xFFFFFF]': 'Valid range: [0x0, 0xFFFFFF]',
        '是否使能加边框。': 'Whether to enable border.',
        'Y：打开': 'Y: On',
        '左边框宽度。': 'Left border width.',
        '合法取值范围为[0, 14]，并且只能取偶数值。': 'Valid range: [0, 14], must be even values.',
        '边框未使能情况下，显示为0。': 'When border is not enabled, displays 0.',
        '右边框宽度。': 'Right border width.',
        '上边框宽度。': 'Top border width.',
        '下边框宽度。': 'Bottom border width.',
        '边框颜色,16进制表示。': 'Border color, hexadecimal representation.',
        '边框未使能情况下，显示为0x0。': 'When border is not enabled, displays 0x0.',
        '通道Sharpen开关。': 'Channel sharpen switch.',
        '通道Sharpen强度。': 'Channel sharpen strength.',
        '通道输出YUV 行Stride对齐。': 'Channel output YUV row stride alignment.',
        '通道模式。': 'Channel mode.',
        'USER：USER模式；': 'USER: USER mode;',
        'AUTO：AUTO模式。': 'AUTO: AUTO mode.',
        '通道的目标输出宽度。': 'Channel target output width.',
        '通道的目标输出高度。': 'Channel target output height.',
        '通道帧率控制：源帧率。': 'Channel frame rate control: source frame rate.',
        '通道帧率控制：目标帧率。': 'Channel frame rate control: target frame rate.',
        '用户获取通道图像的队列长度。': 'Queue length for user to get channel images.',
        '用户获取通道图像的队列长度<span': 'Queue length for user to get channel images<span',
        '用户VB池pool_id。绑定到用户VB池时显示VB池id号，解绑后显示"-"。': 'User VB pool pool_id. Displays VB pool ID when bound, displays "-" after unbinding.',
        '扩展通道属性': 'Extended channel attributes',
        '扩展通道ID号。': 'Extended channel ID number.',
        '扩展通道的源通道。': 'Extended channel source channel.',
        '扩展通道的输出宽度。': 'Extended channel output width.',
        '扩展通道的输出高度。': 'Extended channel output height.',
        '扩展通道帧率控制的源帧率。': 'Extended channel frame rate control source frame rate.',
        '扩展通道帧率控制的目标帧率。': 'Extended channel frame rate control target frame rate.',
        '扩展通道输出<span': 'Extended channel output<span',
        '扩展通道输入源位置。': 'Extended channel input source position.',
        '物理通道缩放系数类型。': 'Physical channel scaling factor type.',
        'NORMAL：通过sys接口配置的缩放系数。': 'NORMAL: Scaling factor configured through sys interface.',
        'BILINEAR：双线性缩放系数。': 'BILINEAR: Bilinear scaling factor.',
        '通道后处理信息': 'Channel post-processing info',
        '固定旋转的角度。': 'Fixed rotation angle.',
        'N：关闭': 'N: Off',
        '通道CoverEx数量。': 'Number of channel CoverEx.',
        '通道MosaicEx数量。': 'Number of channel MosaicEx.',
        '通道Line数量。': 'Number of channel Line.',
        '通道OSD数量。': 'Number of channel OSD.',
        '最后一次通道亮度和统计数量。': 'Last channel luminance and statistics count.',
        '通道aivdec视频增强': 'Channel aivdec video enhancement',
        '低延时属性': 'Low delay attributes',
        '用户设置的低延时使能。': 'User-set low delay enable.',
        'N：不使能；': 'N: Disable;',
        'Y：使能。': 'Y: Enable.',
        '低延时水线。': 'Low delay watermark.',
        '有效范围：最小值为16，最大值为输出图像高度。': 'Valid range: minimum 16, maximum output image height.',
        '单buffer使能。': 'Single buffer enable.',
        '单buffer物理地址。': 'Single buffer physical address.',
        '实际生效的低延时使能。': 'Actual effective low delay enable.',
        '展宽属性': 'Spread attributes',
        '展宽使能开关。': 'Spread enable switch.',
        '展宽强度系数。': 'Spread intensity coefficient.',
        'LDC_V1属性': 'LDC V1 attributes',
        'LDC开关。': 'LDC switch.',
        '不保持幅形比。': 'Do not maintain aspect ratio.',
        '不保持幅形比时候生效。': 'Takes effect when aspect ratio is not maintained.',
        '水平方向上的Crop比例，最大Crop为原图的1/6。': 'Horizontal crop ratio, maximum crop is 1/6 of the original image.',
        '垂直方向上的Crop比例。': 'Vertical crop ratio.',
        '不保持幅形比时候生效，最大Crop为原图的1/6。': 'Takes effect when aspect ratio is not maintained, maximum crop is 1/6 of the original image.',
        '保持幅形比时候生效。': 'Takes effect when aspect ratio is maintained.',
        '水平和垂直方向上的整体Crop比例，最大Crop为原图的1/6。': 'Overall horizontal and vertical crop ratio, maximum crop is 1/6 of the original image.',
        '校正中心点的X坐标偏移。': 'Correction center point X coordinate offset.',
        '校正中心点的Y坐标偏移。': 'Correction center point Y coordinate offset.',
        '校正强度系数。': 'Correction intensity coefficient.',
        'LDC_V3属性': 'LDC V3 attributes',
        '水平方向镜头有效焦距。': 'Horizontal effective focal length.',
        '参数范围：[64*10^2,1173417*10^2]': 'Parameter range: [64*10^2, 1173417*10^2]',
        '垂直方向镜头有效焦距。': 'Vertical effective focal length.',
        '光心X坐标。': 'Optical center X coordinate.',
        '参数范围：[0.35* Width*10^2，0.65* Width *10^2], Width为图像宽。': 'Parameter range: [0.35*Width*10^2, 0.65*Width*10^2], Width is image width.',
        '光心Y坐标。': 'Optical center Y coordinate.',
        '参数范围：[0.35* Height*10^2，0.65* Height*10^2], Height为图像宽。': 'Parameter range: [0.35*Height*10^2, 0.65*Height*10^2], Height is image height.',
        '镜头畸变系数。参数范围：[0,32768]': 'Lens distortion coefficient. Parameter range: [0, 32768]',
        '镜头畸变系数，其中[0]固定为1*10^5，其他成员范围均为[-16*10^5,16*10^5]。': 'Lens distortion coefficient, [0] fixed at 1*10^5, other members range: [-16*10^5, 16*10^5].',
        '镜头畸变系数。每个成员范围均为[-16*10^5,16*10^5]。': 'Lens distortion coefficient. Each member range: [-16*10^5, 16*10^5].',
        '任意角度旋转属性': 'Arbitrary angle rotation attributes',
        '任意角度旋转使能开关。': 'Arbitrary angle rotation enable switch.',
        '旋转类型。': 'Rotation type.',
        'FREE：任意角度旋转': 'FREE: Arbitrary angle rotation',
        'FREE_HP：高精度任意角度旋转': 'FREE_HP: High precision arbitrary angle rotation',
        '任意角度旋转模式：': 'Arbitrary angle rotation mode:',
        'ALL：全模式；': 'ALL: Full mode;',
        'TYPICAL：经典模式；': 'TYPICAL: Classic mode;',
        'INSIDE：无黑边模式。': 'INSIDE: No black border mode.',
        '旋转角度。任意角度旋转时范围：[0, 360]；高精度任意角度旋转时范围：[0, 36000]。': 'Rotation angle. Arbitrary rotation range: [0, 360]; high precision arbitrary rotation range: [0, 36000].',
        '校正中心点的X坐标偏移。仅TYPICAL模式有效。': 'Correction center point X offset. Only valid in TYPICAL mode.',
        '校正中心点的Y坐标偏移。仅TYPICAL模式有效。': 'Correction center point Y offset. Only valid in TYPICAL mode.',
        '输出图像宽度。': 'Output image width.',
        '输出图像高度。': 'Output image height.',
        '鱼眼属性': 'Fisheye attributes',
        '通道鱼眼使能开关。': 'Channel fisheye enable switch.',
        '鱼眼安装模式。': 'Fisheye mount mode.',
        '校正区域数目。': 'Number of correction regions.',
        '背景色使能。': 'Background color enable.',
        '背景色，取值范围：[0, 0xFFFFFF]': 'Background color, range: [0, 0xFFFFFF]',
        '图像中心点与物理中心点的水平偏移量。': 'Horizontal offset between image center and physical center.',
        '图像中心点与物理中心点的垂直偏移量。': 'Vertical offset between image center and physical center.',
        '梯形校正强度系数。': 'Trapezoid correction intensity coefficient.',
        '扇形校正强度。': 'Fan correction intensity.',
        '鱼眼区域属性': 'Fisheye region attributes',
        '校正区域序号，取值范围：[0, 3]': 'Correction region index, range: [0, 3]',
        '校正模式。': 'Correction mode.',
        '校正区域所对应原图的内半径，仅在360全景模式时有效。': 'Inner radius of the original image corresponding to the correction region, only valid in 360 panoramic mode.',
        '校正区域所对应原图的外半径<span': 'Outer radius of the original image corresponding to the correction region<span',
        '校正区域PTZ参数的Pan值。': 'PTZ parameter Pan value for the correction region.',
        '校正区域PTZ参数的Tilt值。': 'PTZ parameter Tilt value for the correction region.',
        '校正区域PTZ参数的水平Zoom值。': 'PTZ parameter horizontal Zoom value for the correction region.',
        '校正区域PTZ参数的垂直Zoom值。': 'PTZ parameter vertical Zoom value for the correction region.',
        '校正区域的输出位置的X坐标。': 'X coordinate of the output position of the correction region.',
        '校正区域的输出位置的Y坐标。': 'Y coordinate of the output position of the correction region.',
        '校正区域的输出宽度。': 'Output width of the correction region.',
        '校正区域的输出高度。': 'Output height of the correction region.',
        '在线模式的帧中断属性': 'Online mode frame interrupt attributes',
        '在线使用的帧中断类型。': 'Frame interrupt type used online.',
        'START：帧起始中断；': 'START: Frame start interrupt;',
        'EARLY：帧起始延时中断；': 'EARLY: Frame start delayed interrupt;',
        'EARLY_END：帧起始延时中断和帧完成中断。': 'EARLY_END: Frame start delayed interrupt and frame completion interrupt.',
        '非起始中断类型时，使用的延时行数。': 'Number of delay lines used for non-start interrupt types.',
        'VPSS组节点状态': 'VPSS group node status',
        '可用节点数。': 'Number of available nodes.',
        '已用节点数。': 'Number of used nodes.',
        'Delay队列长度。': 'Delay queue length.',
        'backup帧占用状态。': 'Backup frame occupancy status.',
        '当前帧状态。': 'Current frame status.',
        'VPSS Grp工作状态信息，时间单位（us）': 'VPSS group working status info, time unit (us)',
        '接收到的图像数。': 'Number of received images.',
        'Preview模式下，因队列满而丢弃的图像数。': 'Number of images dropped due to full queue in Preview mode.',
        'NewDo次数。图像更新，硬件工作次数。': 'NewDo count. Image updated, hardware working count.',
        'OldDo次数。图像不更新，硬件工作次数。': 'OldDo count. Image not updated, hardware working count.',
        'NewUnDo次数。图像更新，硬件不工作次数。': 'NewUnDo count. Image updated, hardware not working count.',
        'OldUnDo次数。图像不更新，硬件不工作次数。': 'OldUnDo count. Image not updated, hardware not working count.',
        'Start任务失败次数。': 'Start task failure count.',
        '当前完成任务的耗时。': 'Current completed task time cost.',
        '历史上耗时最长任务的执行时间。': 'Historical maximum task execution time.',
        'Grp提交到的IP号。显示为"-"时表示该信息无效或Grp为VGS组。': 'IP number to which the group is submitted. "-" indicates invalid info or the group is a VGS group.',
        '0：IP0': '0: IP0',
        '1：IP1': '1: IP1',
        '2：IP2': '2: IP2',
        '其他值对应的IP可以类推。': 'Other values correspond to IP numbers by analogy.',
        '取值范围：[0, OT_VPSS_IP_NUM)': 'Valid range: [0, OT_VPSS_IP_NUM)',
        'VPSS通道输出信息': 'VPSS channel output info',
        '当前VPSS接收图像实际属性': 'Current VPSS received image actual attributes',
        '输入图像实际宽度': 'Actual input image width',
        '输入图像实际高度': 'Actual input image height',
        '输入图像实际像素格式': 'Actual input image pixel format',
        '输入图像实际视频格式': 'Actual input image video format',
        '输入图像实际动态范围': 'Actual input image dynamic range',
        '输入图像压缩模式：': 'Input image compression mode:',
        'NONE：非压缩；': 'NONE: Uncompressed;',
        'SEG：非紧凑段压缩；': 'SEG: Non-compact segment compression;',
        'SEG_COMPACT：紧凑段压缩；': 'SEG_COMPACT: Compact segment compression;',
        'TILE：Tile压缩。': 'TILE: Tile compression.',
        'LINE：行压缩。': 'LINE: Line compression.',
        '在线模式第一帧pts': 'Online mode first frame pts',
        '在线模式当前帧pts': 'Online mode current frame pts',
        '通道使能。': 'Channel enable.',
        '目标图像的宽度，以像素为单位。如果通道调用旋转功能，则显示的是旋转之后的宽度。': 'Target image width in pixels. If rotation is enabled on the channel, displays the width after rotation.',
        '目标图像的高度，以像素为单位。如果通道调用旋转功能，则显示的是旋转之后的高度。': 'Target image height in pixels. If rotation is enabled on the channel, displays the height after rotation.',
        '目标图像的像素格式。': 'Target image pixel format.',
        '目标图像的视频格式。': 'Target image video format.',
        '目标图像的动态范围。': 'Target image dynamic range.',
        '压缩模式：': 'Compression mode:',
        '成功发送的图像数量。': 'Number of successfully sent images.',
        '通道输出的实时帧率。扩展通道如果后端没有绑定其它模块则不统计实时帧率。': 'Channel output real-time frame rate. Extended channels do not count real-time frame rate if no backend module is bound.',
        '图像处理时间。': 'Image processing time.',
        'VPSS硬件工作状态信息': 'VPSS hardware work status info',
        '链中断次数。': 'Link interrupt count.',
        'Bus Error中断次数。': 'Bus error interrupt count.',
        '启动VPSS0成功次数。': 'VPSS0 start success count.',
        '启动VPSS0失败次数。': 'VPSS0 start failure count.',
        '读取VPSS0 NodeId错误次数。': 'VPSS0 NodeId read error count.',
        '启动VPSS1成功次数。': 'VPSS1 start success count.',
        '启动VPSS1失败次数。': 'VPSS1 start failure count.',
        '读取VPSS1NodeId错误次数。': 'VPSS1 NodeId read error count.',
        '启动VPSS2成功次数。': 'VPSS2 start success count.',
        '启动VPSS2失败次数。': 'VPSS2 start failure count.',
        '读取VPSS2NodeId错误次数。': 'VPSS2 NodeId read error count.',
        'VPSS硬件节点队列状态信息': 'VPSS hardware node queue status info',
        'Free队列上可用节点个数。': 'Number of available nodes on the Free queue.',
        'Wait队列上待处理节点个数。': 'Number of pending nodes on the Wait queue.',
        'VPSS0的busy0队列上的节点个数。': 'Number of nodes on VPSS0 busy0 queue.',
        'VPSS0的busy1队列上的节点个数。': 'Number of nodes on VPSS0 busy1 queue.',
        'VPSS0用于工作的busy队列id号。': 'VPSS0 working busy queue ID.',
        'VPSS1的busy0队列上的节点个数。': 'Number of nodes on VPSS1 busy0 queue.',
        'VPSS1的busy1队列上的节点个数。': 'Number of nodes on VPSS1 busy1 queue.',
        'VPSS1用于工作的busy队列id号。': 'VPSS1 working busy queue ID.',
        'VPSS2的busy0队列上的节点个数。': 'Number of nodes on VPSS2 busy0 queue.',
        'VPSS2的busy1队列上的节点个数。': 'Number of nodes on VPSS2 busy1 queue.',
        'VPSS2用于工作的busy队列id号。': 'VPSS2 working busy queue ID.',
        'Proc队列上的节点个数。': 'Number of nodes on the Proc queue.',
        'VPSS中断工作状态信息，时间单位（us）': 'VPSS interrupt work status info, time unit (us)',
        '最近一次的1秒内中断执行次数。': 'Interrupt execution count in the most recent 1 second.',
        '历史上的1秒内最大的中断执行次数。': 'Historical maximum interrupt execution count in 1 second.',
        '最近一次执行中断的执行耗时。': 'Execution time of the most recent interrupt.',
        '执行一次中断的最大耗时。': 'Maximum execution time of a single interrupt.',
        '最近一秒执行中断的执行耗时。': 'Execution time of interrupts in the most recent 1 second.',
        '历史上一秒执行中断的最大执行耗时。': 'Historical maximum interrupt execution time in 1 second.',
        'VPSS通道输出分辨率指的是缩放模块的输出分辨率。': 'VPSS channel output resolution refers to the output resolution of the scaling module.',
        'VPSS LDCI的proc信息（vpss ldci attr）仅SS524V100/SS522V100支持。开启LDCI功能时才会显示具体的属性值，否则只显示属性字段。': 'VPSS LDCI proc info (vpss ldci attr) is only supported by SS524V100/SS522V100. Specific attribute values are displayed only when the LDCI function is enabled; otherwise, only attribute fields are shown.',
        'SS524V100/SS522V100/Hi3403V100的VPSS IP个数是1，vpss hardware node queue和vpss int work status中只有VPSS0相关的信息。': 'SS524V100/SS522V100/Hi3403V100 have 1 VPSS IP. vpss hardware node queue and vpss int work status only contain VPSS0-related info.',
        'SS528V100/SS625V100/SS524V100/SS522V100/Hi3403V100/SS626V100无Proc队列，Proc队列的节点数是0。': 'SS528V100/SS625V100/SS524V100/SS522V100/Hi3403V100/SS626V100 have no Proc queue. Proc queue node count is 0.',
        'Hi3403V100未开启OT_LDC_V3功能时proc信息不显示src_calibration_ratio和src_calibration_ratio_next。': 'When Hi3403V100 does not enable OT_LDC_V3, proc info does not display src_calibration_ratio and src_calibration_ratio_next.',
        'Hi3403V100/SS626V100 vpss chn proc ex部分 proc信息仅固定角度旋转和亮度和有效。': 'For Hi3403V100/SS626V100, vpss chn proc ex proc info is only valid for fixed angle rotation and luma.',
        'vpss module param中schedule_mode参数是在SYS接口设置的，仅SS528V100/SS625V100/SS524V100/SS522V100/SS626V100支持。': 'The schedule_mode parameter in vpss module param is set through the SYS interface and is only supported by SS528V100/SS625V100/SS524V100/SS522V100/SS626V100.',
        '仅Hi3403V100和SS626V100支持任意角度旋转。': 'Only Hi3403V100 and SS626V100 support arbitrary angle rotation.',
        'vpss chn output status中的proc_time仅对物理通道生效。': 'proc_time in vpss chn output status only takes effect for physical channels.',
        '仅SS528V100/SS625V100/SS524V100/SS522V100支持3DNR V1版本参数和3DNR高级参数。': 'Only SS528V100/SS625V100/SS524V100/SS522V100 support 3DNR V1 parameters and 3DNR advanced parameters.',
        '仅Hi3403V100支持3DNR V2版本参数。': 'Only Hi3403V100 supports 3DNR V2 parameters.',
        'Hi3403V100 VPSS开启mcf_en时，通道处理比较复杂，部分通道处理相关proc信息未显示。': 'When Hi3403V100 VPSS enables mcf_en, channel processing is more complex, and some channel processing-related proc info is not displayed.',
        'grp work status中cost_time和max_cost_time仅离线模式生效；对于Hi3403V100，开启mcf_en的组cost_time和max_cost_time无效。': 'cost_time and max_cost_time in grp work status only take effect in offline mode; for Hi3403V100, groups with mcf_en enabled have invalid cost_time and max_cost_time.',
        'Hi3403V100 3DNR参数中sfn_x四个参数使用下划线隔开。': 'In Hi3403V100 3DNR parameters, the four sfn_x parameters are separated by underscores.',
        'vpss grp param中参数对于Hi3403V100无效。': 'Parameters in vpss grp param are invalid for Hi3403V100.',
        'buffer share、低延时的使能状态，用户设置的和实际生效的使用2个参数分别显示，互斥功能检查按用户设置的状态做检查。': 'For buffer share and low delay enable status, user settings and actual effective status are displayed using separate parameters. Mutually exclusive function checks use the user-set status.',
        'VPSS 各通道静态配置': 'VPSS channel static configuration',
        'VPSS该通道是否支持超过15倍缩小。': 'Whether this VPSS channel supports scaling down more than 15x.',
        'VPSS该通道是否支持通道后处理。': 'Whether this VPSS channel supports channel post-processing.',
        'VPSS 各物理通道属性1': 'VPSS physical channel attributes 1',
        'VPSS 各物理通道属性2': 'VPSS physical channel attributes 2',
        'VPSS 各物理通道属性3': 'VPSS physical channel attributes 3',
        '提前发送功能实际生效的值。': 'Actual effective value of the early send function.',
        'VPSS Grp属性1': 'VPSS group attributes 1',
        'VPSS Grp属性2': 'VPSS group attributes 2',
        'VPSS 组CROP信息': 'VPSS group crop info',
        '输入YUV的量化范围。': 'Input YUV quantization range.',
        'LIMITED：YUV图像量化范围是[16, 235]。': 'LIMITED: YUV image quantization range is [16, 235].',
        'FULL：YUV图像量化范围是[0, 255]。': 'FULL: YUV image quantization range is [0, 255].',
        '暗区增益控制强度，用于抑制暗区噪声。': 'Dark area gain control strength, used to suppress dark area noise.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制提亮程度，曲线呈GAUSS分布，该参数为GAUSS分布最大值。': 'Local histogram equalization result and original image fusion weight curve, controls brightness enhancement based on luminance, with GAUSS distribution. This parameter is the maximum value of the GAUSS distribution.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制提亮程度，曲线呈GAUSS分布，该参数为GAUSS分布均方差。': 'Local histogram equalization result and original image fusion weight curve, controls brightness enhancement based on luminance, with GAUSS distribution. This parameter is the mean square error of the GAUSS distribution.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制提亮程度，曲线呈GAUSS分布，该参数为GAUSS分布数学期望。': 'Local histogram equalization result and original image fusion weight curve, controls brightness enhancement based on luminance, with GAUSS distribution. This parameter is the mathematical expectation of the GAUSS distribution.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制变暗程度，曲线呈GAUSS分布，该参数为GAUSS分布最大值。': 'Local histogram equalization result and original image fusion weight curve, controls darkening based on luminance, with GAUSS distribution. This parameter is the maximum value of the GAUSS distribution.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制变暗程度，曲线呈GAUSS分布，该参数为GAUSS分布均方差。': 'Local histogram equalization result and original image fusion weight curve, controls darkening based on luminance, with GAUSS distribution. This parameter is the mean square error of the GAUSS distribution.',
        '局域直方图均衡结果与原图融合权重曲线，根据亮度控制变暗程度，曲线呈GAUSS分布，该参数为GAUSS分布数学期望。': 'Local histogram equalization result and original image fusion weight curve, controls darkening based on luminance, with GAUSS distribution. This parameter is the mathematical expectation of the GAUSS distribution.',
        '该状态是实际生效的状态，不是接口设置的状态。': 'This status is the actual effective status, not the interface-set status.',
        'VPSS Grp属性2': 'VPSS group attributes 2',
        '记录当前VPSS属性配置以及状态信息。': 'Records current VPSS attribute configuration and status information.',

        # AI section translations
        'AI设备号。': 'AI device number.',
        'AI工作模式。': 'AI working mode.',
        'i2s_mas': 'i2s_mas',
        'I2S主模式。': 'I2S master mode.',
        'I2S从模式。': 'I2S slave mode.',
        '标准PCM主模式。': 'Standard PCM master mode.',
        '标准PCM从模式。': 'Standard PCM slave mode.',
        '非标准PCM主模式。': 'Non-standard PCM master mode.',
        '非标准PCM从模式。': 'Non-standard PCM slave mode.',
        '采样率。': 'Sample rate.',
        '取值：{8k~96k}。': 'Value: {8k~96k}.',
        '取值：{8k~96k}': 'Value: {8k~96k}',
        '采样精度。': 'Sample bit width.',
        '取值：{8bit, 16bit}。': 'Value: {8bit, 16bit}.',
        '取值：{8bit, 16bit}': 'Value: {8bit, 16bit}',
        '通道个数。': 'Number of channels.',
        '取值：{1, 2, 4, 8, 16}。': 'Value: {1, 2, 4, 8, 16}.',
        '取值：{1, 2}': 'Value: {1, 2}',
        '时钟选择。': 'Clock select.',
        '声音模式。': 'Sound mode.',
        'mono：单声道；': 'mono: Mono;',
        'stereo：立体声。': 'stereo: Stereo.',
        '每帧的采样点个数。': 'Number of sample points per frame.',
        '8bit扩展标志。': '8-bit expansion flag.',
        '帧缓存数目。': 'Number of frame buffers.',
        '中断计数。': 'Interrupt count.',
        '完成1 帧音频数据采集后，此值加1。': 'Increments by 1 after completing 1 frame of audio data capture.',
        '如果此值未递增，说明与外围codec 对接有问题。': 'If this value does not increment, there may be an issue with the external codec connection.',
        '发送1 帧音频数据后，此值加1。': 'Increments by 1 after sending 1 frame of audio data.',
        'Fifo 上溢中断计数。': 'FIFO overflow interrupt count.',
        'AI 接收fifo 满，发生溢出时，此值加1。': 'Increments by 1 when the AI receive FIFO overflows.',
        'Fifo 下溢中断计数。': 'FIFO underflow interrupt count.',
        'AO 发送fifo 空，发生溢出时，此值加1。': 'Increments by 1 when the AO send FIFO underflows.',
        'DMA buffer 满中断计数。': 'DMA buffer full interrupt count.',
        'AI 接收数据的DMA buffer 满时，此值加1。': 'Increments by 1 when the DMA buffer for AI data reception is full.',
        'DMA buffer 空中断计数。': 'DMA buffer empty interrupt count.',
        'AO 发送数据的DMA buffer 空时，此值加1。': 'Increments by 1 when the DMA buffer for AO data transmission is empty.',
        '帧间隔时间。以us 为单位。': 'Frame interval time in us.',
        '由此项可以计算出实际的音频采样率。例如当此项为40000us 左右、每帧采样点个数配置为320时，可以计算出每秒采样8000 点，即采样率为8kHz。': 'The actual audio sample rate can be calculated from this value. For example, when this value is around 40000us and the number of sample points per frame is 320, it calculates to 8000 samples per second, i.e., 8kHz sample rate.',
        '帧间隔最长时间。': 'Maximum frame interval time.',
        '此项统计系统从开始到当前为止最长的帧间隔时间。': 'This value records the longest frame interval from system start to the present.',
        '此项统计系统从开始到当前为止最长的DMA 中断处理时间。': 'This value records the longest DMA interrupt processing time from system start to the present.',
        '一次DMA传输的长度（字节）。': 'Length of one DMA transfer (bytes).',
        'DMA 中断处理时间。': 'DMA interrupt processing time.',
        'DMA 中断处理最长时间。': 'Maximum DMA interrupt processing time.',
        'DMA buffer的物理地址。': 'Physical address of the DMA buffer.',
        'DMA buffer的大小。': 'DMA buffer size.',
        'DMA buffer的读指针相对于起始地址的偏移量。': 'Offset of the DMA buffer read pointer from the start address.',
        'DMA buffer的写指针相对于起始地址的偏移量。': 'Offset of the DMA buffer write pointer from the start address.',
        'AI设备的声道模式。': 'AI device channel mode.',
        '静音是否开启标志，对AI设备无效。': 'Mute flag. Invalid for AI devices.',
        '音量大小，对AI设备无效。': 'Volume level. Invalid for AI devices.',
        'AI通道号。': 'AI channel number.',
        'AI通道号。': 'AI channel number.',
        '通道状态。': 'Channel status.',
        'orig：初始状态；': 'orig: Initial state;',
        'enable：启用；': 'enable: Enabled;',
        'disable：禁用。': 'disable: Disabled.',
        '通道工作模式。': 'Channel working mode.',
        'normal：正常模式；': 'normal: Normal mode;',
        'fast：快速模式。': 'fast: Fast mode.',
        '帧buffer满的次数。': 'Frame buffer full count.',
        '用户态发送时的丢帧数。': 'Frame loss count during user-space transmission.',
        '用户设置的音频帧缓存深度。': 'User-set audio frame buffer depth.',
        '通道Buffer中第一个32位数据是否为静音数据。': 'Whether the first 32-bit data in the channel buffer is mute data.',
        '通道Buffer中第二个32位数据是否为静音数据。': 'Whether the second 32-bit data in the channel buffer is mute data.',
        '用户获取的帧计数': 'User frame get count',
        '用户释放的帧计数。': 'User frame release count.',
        '该通道是否启用了重采样功能。': 'Whether resampling is enabled for this channel.',
        'Y：启用重采样功能；': 'Y: Resampling enabled;',
        'N：关闭重采样功能。': 'N: Resampling disabled.',
        '该通道重采样时，输入给重采样的数据帧中包含的采样点数目。': 'Number of sample points in the input data frame for resampling.',
        '该通道重采样时，输入给重采样的数据帧的采样率。': 'Sample rate of the input data frame for resampling.',
        '该通道重采样时，重采样后的音频帧采样率。': 'Sample rate of the resampled audio frame.',
        '通道启用声音质量增强功能使能。': 'Whether voice quality enhancement (VQE) is enabled.',
        'Y：启用声音质量增强功能；': 'Y: Voice quality enhancement enabled;',
        'N：关闭声音质量增强功能。': 'N: Voice quality enhancement disabled.',
        '声音质量增强的工作模式。': 'Voice quality enhancement working mode.',
        'comm：一般模式；': 'comm: Communication mode;',
        'music：音乐模式；': 'music: Music mode;',
        'noisy：噪声模式。': 'noisy: Noisy mode.',
        'VQE处理的数据采样率。': 'Data sample rate for VQE processing.',
        'VQE处理的数据帧长中的采样点数目。': 'Number of sample points in the VQE processing data frame.',
        'Agc功能是否使能。': 'Whether AGC function is enabled.',
        'Y：使能；': 'Y: Enable;',
        'N：禁用。': 'N: Disable.',
        'Eq功能是否使能。': 'Whether EQ function is enabled.',
        'Hpf功能是否使能。': 'Whether HPF function is enabled.',
        'Rnr功能是否使能。': 'Whether RNR function is enabled.',
        'Hdr功能是否使能。': 'Whether HDR function is enabled.',
        'Drc功能是否使能。': 'Whether DRC function is enabled.',
        '该通道是否在向文件存储通道数据。': 'Whether this channel is storing channel data to a file.',
        'Y：启用向文件存储通道数据功能；': 'Y: File storage enabled;',
        'N：关闭向文件存储通道数据功能。': 'N: File storage disabled.',
        '通道启用自动增益控制功能使能。': 'Whether automatic gain control (AGC) is enabled.',
        'Y：启用自动增益控制功能；': 'Y: AGC enabled;',
        'N：关闭自动增益控制功能。': 'N: AGC disabled.',
        '是否采用用户模式。': 'Whether to use user mode.',
        'N：自动模式；': 'N: Auto mode;',
        'Y：用户模式。': 'Y: User mode.',
        '噪声抑制开关；范围{0, 1}。': 'Noise suppression switch; range: {0, 1}.',
        '调整速度；范围：[0 ~ 10]dB/s。': 'Adjustment speed; range: [0 ~ 10]dB/s.',
        '提高信噪比开关；范围：[0:不提升, 1:上限3dB, 2:上限6dB]': 'SNR improvement switch; range: [0: No improvement, 1: Max 3dB, 2: Max 6dB]',
        '最大增益；范围：[0 ~ 30]dB。': 'Maximum gain; range: [0 ~ 30]dB.',
        '噪声底线；范围：[-65 ~ -20]dB。': 'Noise floor; range: [-65 ~ -20]dB.',
        '输出模式，低于NoiseFloor的信号输出静音；范围：[0：关闭；1：打开]': 'Output mode, signals below NoiseFloor are muted; range: [0: Off, 1: On]',
        '目标电平；范围：[-40 ~ -1]dB；调整步长1dB。': 'Target level; range: [-40 ~ -1]dB; step: 1dB.',
        '打开高通滤波标志；': 'HPF enable flag;',
        '范围：[0:关闭, 1:80Hz, 2:120Hz, 3:150Hz, 4:300Hz, 5:500Hz]': 'Range: [0: Off, 1: 80Hz, 2: 120Hz, 3: 150Hz, 4: 300Hz, 5: 500Hz]',
        '通道启用均衡器功能使能。': 'Whether equalizer (EQ) function is enabled.',
        'Y：启用均衡器功能；': 'Y: EQ enabled;',
        'N：关闭均衡器功能。': 'N: EQ disabled.',
        '频段范围：[-50, 50]dB。': 'Frequency band range: [-50, 50]dB.',
        '记录当前音频输入设备及通道的属性配置以及状态信息。': 'Records the current audio input device and channel attribute configuration and status information.',
        '在实际使用中，VQE状态信息只会打印出使能后的功能模块信息。': 'In actual use, VQE status info only prints the enabled functional module information.',

        # AO section
        'AO设备号。': 'AO device number.',
        'AO工作模式。': 'AO working mode.',
        'AO设备静音功能是否开启。': 'Whether the AO device mute function is enabled.',
        'Y：静音打开；': 'Y: Mute on;',
        'N：静音关闭。': 'Y: Mute off.',
        'AO设备的输出音量大小。': 'AO device output volume level.',
        'AO通道号。': 'AO channel number.',
        '通道buffer的读指针。': 'Channel buffer read pointer.',
        '通道buffer的写指针。': 'Channel buffer write pointer.',
        '帧buffer空的次数。': 'Frame buffer empty count.',
        '记录当前AO属性配置以及状态信息。': 'Records current AO attribute configuration and status information.',

        # AENC section
        '记录当前音频编码属性配置以及状态信息。': 'Records current audio encoding attribute configuration and status information.',

        # ADEC section
        '记录当前音频解码属性配置以及状态信息。': 'Records current audio decoding attribute configuration and status information.',

        # ACODEC section
        '记录当前音频Codec寄存器信息。': 'Records current audio codec register information.',

        # VDEC section
        '记录当前VDEC属性配置以及状态信息。': 'Records current VDEC attribute configuration and status information.',

        # VFMW section
        '记录当前VESC属性配置以及状态信息。': 'Records current VFMW attribute configuration and status information.',

        # VDA section
        '记录当前VDA属性配置以及状态信息。': 'Records current VDA attribute configuration and status information.',

        # AVS section
        '记录当前AVS属性配置以及状态信息。': 'Records current AVS attribute configuration and status information.',

        # DIS section
        '记录当前DIS属性配置以及状态信息。': 'Records current DIS attribute configuration and status information.',

        # GDC section
        '记录当前GDC属性配置以及状态信息。': 'Records current GDC attribute configuration and status information.',

        # DCC section
        '记录当前DCC属性配置以及数据信息。如果未使能DCC模块，则只打印出DCC属性名而不打印属性值。': 'Records current DCC attribute configuration and data information. If the DCC module is not enabled, only DCC attribute names are printed without attribute values.',

        # VDEC_ADAPT section
        '记录当前VDEC_ADAPT属性配置以及状态信息。': 'Records current VDEC_ADAPT attribute configuration and status information.',

        # Other common patterns
        '物理通道ID号。': 'Physical channel ID number.',
        '物理通道ID号。': 'Physical channel ID number.',

        # VPSS specific sections
        'VPSS Grp属性1': 'VPSS group attributes 1',
        'VPSS 组CROP信息': 'VPSS group crop info',
        'VPSS LDCI属性': 'VPSS LDCI attributes',
        'VPSS 各物理通道属性1': 'VPSS physical channel attributes 1',
        'VPSS 各物理通道属性2': 'VPSS physical channel attributes 2',
        'VPSS 各物理通道属性3': 'VPSS physical channel attributes 3',

        # Notes
        '组输入图像最大宽度。单位：像素。': 'Group input image maximum width. Unit: pixel.',
        '组输入图像最大高度。单位：像素。': 'Group input image maximum height. Unit: pixel.',
        '组输入图像像素格式。': 'Group input image pixel format.',
        'GRP源帧率。': 'Group source frame rate.',
        'GRP目标帧率。': 'Group destination frame rate.',
    }

    # Simple text replacement for entries with HTML tags mixed in
    # Handle the case where text is inside HTML tags
    # Process common short translations first

    # Sort keys by length (longest first) to avoid partial replacements
    sorted_keys = sorted(translations.keys(), key=len, reverse=True)

    for key in sorted_keys:
        if key in text:
            text = text.replace(key, translations[key])

    return text


def translate_whole_line(line):
    """Translate a single line, preserving code blocks and non-translatable elements."""
    # Skip code blocks and empty lines
    stripped = line.strip()

    # Preserve code blocks
    if stripped.startswith('```'):
        return line

    # Preserve code block content (lines starting with spaces/tabs inside code blocks)
    # Check if this is inside a code block by examining the context

    # Translate the line
    return translate_text(line)


def process_file(input_path, output_path):
    """Process the file and create a translated version."""
    with open(input_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    in_code_block = False
    output_lines = []

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Track code blocks
        if stripped.startswith('```'):
            in_code_block = not in_code_block
            output_lines.append(line)
            continue

        # In code blocks, preserve content exactly
        if in_code_block:
            output_lines.append(line)
            continue

        # Translate line
        translated = translate_whole_line(line)
        output_lines.append(translated)

    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.writelines(output_lines)

    print(f"Translation complete. Output written to {output_path}")


if __name__ == '__main__':
    import sys
    input_file = '/Users/arthurbetter/hi3403-build/hi3403-docs/docs/multimedia/mpp/13-proc调试信息-1316-1329.md'
    output_file = '/Users/arthurbetter/hi3403-build/hi3403-docs/docs/multimedia/mpp/13-proc调试信息-1316-1329.en.md'
    process_file(input_file, output_file)
    print("\n--- Translation Complete ---")
