#!/usr/bin/env python3
"""Translate ALL remaining Chinese text in the proc debug en.md file."""
import re

path = '/Users/arthurbetter/hi3403-build/hi3403-docs/docs/multimedia/mpp/13-proc调试信息-1316-1329.en.md'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# All translations
translations = {
    '记录当前音频输入设备及通道的属性配置以及状态信息。': 'Records the current audio input device and channel attribute configuration and status information.',
    '在实际使用中，VQE状态信息只会打印出使能后的功能模块信息。': 'In actual use, VQE status info only prints enabled functional module information.',
    '记录当前音频编码属性配置以及状态信息。': 'Records current audio encoding attribute configuration and status information.',
    '记录当前音频解码属性配置以及状态信息。': 'Records current audio decoding attribute configuration and status information.',
    '记录当前音频Codec寄存器信息。': 'Records current audio codec register information.',
    '记录当前VDEC属性配置以及状态信息。': 'Records current VDEC attribute configuration and status information.',
    '记录当前VDA属性配置以及状态信息，SS928V100不支持。': 'Records current VDA attribute configuration and status information. Not supported by SS928V100.',
    '记录当前AVS属性配置以及状态信息。目前仅SS928V100支持。': 'Records current AVS attribute configuration and status information. Currently only supported by SS928V100.',
    '记录当前DIS属性配置以及状态信息。': 'Records current DIS attribute configuration and status information.',
    '记录当前GDC属性配置以及状态信息。': 'Records current GDC attribute configuration and status information.',
    '记录当前DCC属性配置以及数据信息。如果未使能DCC模块，则只打印出DCC属性名而不打印属性值。': 'Records current DCC attribute configuration and data information. If the DCC module is not enabled, only DCC attribute names are printed without attribute values.',
    '记录当前VDEC_ADAPT属性配置以及状态信息。': 'Records current VDEC_ADAPT attribute configuration and status information.',
    'I2S1采样率。': 'I2S1 sample rate.',
    'I2S1采样位宽。': 'I2S1 sample bit width.',
    '左声道输入通路选择。': 'Left channel input path selection.',
    '右声道输入通路选择。': 'Right channel input path selection.',
    'ADC时钟沿选择。': 'ADC clock edge selection.',
    'DAC时钟沿选择。': 'DAC clock edge selection.',
    'MCLK时钟沿选择。': 'MCLK clock edge selection.',
    'ADC高通滤波启用标志。': 'ADC high-pass filter enable flag.',
    'y：启用；': 'y: Enabled;',
    'n：未启用。': 'n: Not enabled.',
    'DAC去加重启用标志。': 'DAC de-emphasis enable flag.',
    '左声道输出音量，单位dB。': 'Left channel output volume in dB.',
    '右声道输出音量，单位dB。': 'Right channel output volume in dB.',
    '左声道ADC输入是否静音。': 'Whether the left channel ADC input is muted.',
    '右声道ADC输入是否静音。': 'Whether the right channel ADC input is muted.',
    '左声道DAC输出是否静音。': 'Whether the left channel DAC output is muted.',
    '右声道DAC输出是否静音。': 'Whether the right channel DAC output is muted.',
    'ADC左声道的下电控制。': 'ADC left channel power down control.',
    'ADC右声道的下电控制。': 'ADC right channel power down control.',
    'DAC左声道的下电控制。': 'DAC left channel power down control.',
    'DAC右声道的下电控制。': 'DAC right channel power down control.',
    '幅形比背景色。': 'Aspect ratio background color.',
    'IO输出模式。': 'IO output mode.',
    '总状态': 'Overall status',
    '左声道输入通路选择。': 'Left channel input path selection.',
    '右声道输入通路选择。': 'Right channel input path selection.',
    'in0_diff：IN0差分；': 'in0_diff: IN0 differential;',
    'in0_left：IN0左声道；': 'in0_left: IN0 left channel;',
    'in0_right：IN0右声道；': 'in0_right: IN0 right channel;',
    'in1_diff：IN1差分；': 'in1_diff: IN1 differential;',
    'in1_left：IN1左声道；': 'in1_left: IN1 left channel;',
    'in1_right：IN1右声道。': 'in1_right: IN1 right channel.',
    'rise：上升沿；': 'rise: Rising edge;',
    'fall：下降沿。': 'fall: Falling edge.',
    '0：未初始化；': '0: Not initialized;',
    '1：初始化1次。': '1: Initialized once.',
    '0：MD；': '0: MD;',
    '1：OD。': '1: OD.',
    '0：背景法；': '0: Background subtraction;',
    '1：帧差法。': '1: Frame difference.',
    '0：8x8；': '0: 8x8;',
    '1：16x16。': '1: 16x16.',
    '通道宽度（单位：像素）。': 'Channel width (unit: pixel).',
    '通道高度（单位：像素）。': 'Channel height (unit: pixel).',
    '通道模式。': 'Channel mode.',
    '工作算法。': 'Working algorithm.',
    '宏块大小。': 'Macroblock size.',
    'VDA实际使用的最大通道数。': 'Maximum number of channels actually used by VDA.',
    'VDA通道属性': 'VDA channel attributes',
    'AVS模块参数': 'AVS module parameters',
    'AVS的工作空间的大小，单位为KB。': 'AVS working set size in KB.',
    'Grp属性': 'Group attributes',
    'VPSS组参数及配置信息': 'VPSS group parameters and configuration info',
    '扩展通道属性': 'Extended channel attributes',
    '低延时属性': 'Low delay attributes',
    '展宽属性': 'Spread attributes',
    'LDC_V1属性': 'LDC V1 attributes',
    'LDC_V3属性': 'LDC V3 attributes',
    '任意角度旋转属性': 'Arbitrary angle rotation attributes',
    '鱼眼属性': 'Fisheye attributes',
    '鱼眼区域属性': 'Fisheye region attributes',
    '在线模式的帧中断属性': 'Online mode frame interrupt attributes',
    'VPSS组节点状态': 'VPSS group node status',
    'VPSS Grp工作状态信息，时间单位（us）': 'VPSS group working status info, time unit (us)',
    'VPSS硬件工作状态信息': 'VPSS hardware work status info',
    'VPSS硬件节点队列状态信息': 'VPSS hardware node queue status info',
    'VPSS中断工作状态信息，时间单位（us）': 'VPSS interrupt work status info, time unit (us)',
    '当前VPSS接收图像实际属性': 'Current VPSS received image actual attributes',
    'VPSS通道输出信息': 'VPSS channel output info',
    '通道后处理信息': 'Channel post-processing info',
    '通道裁剪信息': 'Channel crop info',
    'VPSS LDCI属性': 'VPSS LDCI attributes',
    '3DNR标准参数版本': '3DNR standard parameter version',
    '3DNR工作模式。': '3DNR working mode.',
    'ISO值。': 'ISO value.',
    '空域滤波强度。': 'Spatial filter strength.',
    '调节色度的时滤波器参数。': 'Adjust chroma temporal filter parameters.',
    '调节第0级的空域滤波器参数。': 'Adjust level 0 spatial filter parameters.',
    '调节第0级的时域滤波器参数。': 'Adjust level 0 temporal filter parameters.',
    '调节第1级的空域滤波器参数。': 'Adjust level 1 spatial filter parameters.',
    '调节第1级的时域滤波器参数。': 'Adjust level 1 temporal filter parameters.',
    '调节第2级的空域滤波器参数。': 'Adjust level 2 spatial filter parameters.',
    '调节第2级的时域滤波器参数。': 'Adjust level 2 temporal filter parameters.',
    '调节第3级的空域滤波器参数。': 'Adjust level 3 spatial filter parameters.',
    '调节色度第1级的空域参数。': 'Adjust chroma level 1 spatial parameters.',
    'Limit range模式开关。': 'Limit range mode switch.',
    '4级亮度滤波器使能标识。': '4-level luma filter enable flag.',
    '2级色度滤波器使能标识。': '2-level chroma filter enable flag.',
    '3DNR第0级时域开关。': '3DNR level 0 temporal switch.',
    '3DNR第1级时域开关，一般不建议调试，建议保持为默认值1。': '3DNR level 1 temporal switch. It is generally not recommended to adjust; keep the default value 1.',
    'VPSS 3DNR V1版本标准参数': 'VPSS 3DNR V1 standard parameters',
    'VPSS 3DNR V2版本标准参数': 'VPSS 3DNR V2 standard parameters',
    'VPSS 3DNR高级参数': 'VPSS 3DNR advanced parameters',
    '亮度空域去噪强度（标准参数）': 'Luma spatial denoising strength (standard parameter)',
    '亮度时域去噪强度（标准参数）': 'Luma temporal denoising strength (standard parameter)',
    '色度空域去噪强度（标准参数）': 'Chroma spatial denoising strength (standard parameter)',
    '色度时域去噪强度（标准参数）': 'Chroma temporal denoising strength (standard parameter)',
    '处理输入时产生亮串色现象的能力强度（标准参数）': 'Brightness cross-color artifact suppression strength during input processing (standard parameter)',
    '区域运动阈值（高级参数）': 'Region motion threshold (advanced parameter)',
    '强去噪通道时域空域混合比重（高级参数）': 'Strong denoising channel temporal-spatial blend ratio (advanced parameter)',
    '区域强边缘阈值（高级参数）': 'Region strong edge threshold (advanced parameter)',
    '弱去噪通道时域空域混合比重（高级参数）': 'Weak denoising channel temporal-spatial blend ratio (advanced parameter)',
    '用户设置的输入输出Buffer复用状态。': 'User-set input/output buffer sharing status.',
    '用户设置的输入输出Buffer复用通道号。': 'User-set input/output buffer sharing channel number.',
    '实际生效的输入输出Buffer复用状态。': 'Actual effective input/output buffer sharing status.',
    'X：复用通道号，': 'X: Shared channel number, ',
    'DCI使能状态': 'DCI enable status',
    'IE使能状态。': 'IE enable status.',
    'DEI模式。': 'DEI mode.',
    'DEI最大处理宽度。': 'DEI maximum processing width.',
    'DEI最大处理高度。': 'DEI maximum processing height.',
    'MCF使能。': 'MCF enable.',
    'backup使能状态。在最开始没有帧输入时显示为N，有帧时会根据实际情况显示。': 'Backup enable status. Displays N when no frame input initially, and displays according to actual conditions when frames are available.',
    '3DNR使能。': '3DNR enable.',
    '3DNR模式。': '3DNR mode.',
    '参考帧压缩模式。': 'Reference frame compression mode.',
    '3DNR运动矢量。': '3DNR motion vector.',
    '调度模式，通过SYS接口设置。': 'Scheduling mode, set through the SYS interface.',
    '3DNR延时模式使能。': '3DNR delay mode enable.',
    '组的多任务使能。': 'Group multi-task enable.',
    'VPSS支持输出低延时开关。': 'VPSS supports output low delay switch.',
    'VPSS proc统计处理时间数据开关。': 'VPSS proc statistics processing time data switch.',
    'VPSS组链阈值。': 'VPSS group chain threshold.',
    '关闭时VPSS proc中的cost_time、max_cost_time、proc_time、中断工作时间等信息不进行统计。': 'When disabled, cost_time, max_cost_time, proc_time, interrupt work time and other information in VPSS proc are not counted.',
    '用户做帧率控制。': 'User frame rate control.',
    'DCI强度。': 'DCI intensity.',
    'IE强度。': 'IE intensity.',
    '是否开启尺寸筛选。': 'Whether to enable size filter.',
    '筛选尺寸宽。': 'Filter size width.',
    '筛选尺寸高。': 'Filter size height.',
    '组Mosaic数量。': 'Number of group Mosaic.',
    '组Cover数量。': 'Number of group Cover.',
    '组OSD数量。': 'Number of group OSD.',
    '最后一次提交给组的亮度和任务数。': 'Last submitted group luminance and task count.',
    '幅形比模式。': 'Aspect ratio mode.',
    '视频位置X坐标。手动模式有效。': 'Video position X coordinate. Only valid in manual mode.',
    '视频位置Y坐标。手动模式有效。': 'Video position Y coordinate. Only valid in manual mode.',
    '视频宽度。手动模式有效。': 'Video width. Only valid in manual mode.',
    '视频高度。手动模式有效。': 'Video height. Only valid in manual mode.',
    '是否使能加边框。': 'Whether to enable border.',
    '左边框宽度。': 'Left border width.',
    '合法取值范围为[0, 14]，并且只能取偶数值。': 'Valid range: [0, 14], must be even values.',
    '边框未使能情况下，显示为0。': 'When border is not enabled, displays 0.',
    '右边框宽度。': 'Right border width.',
    '上边框宽度。': 'Top border width.',
    '下边框宽度。': 'Bottom border width.',
    '边框颜色,16进制表示。': 'Border color, hexadecimal representation.',
    '边框未使能情况下，显示为0x0。': 'When border is not enabled, displays 0x0.',
    '正确。': 'Correct.',
    '错误。': 'Error.',
    '第一通道输出图像的颜色格式。': 'First channel output image color format.',
    '第二通道输出图像的颜色格式。': 'Second channel output image color format.',
    '输出分辨率。': 'Output resolution.',
    '输入分辨率。': 'Input resolution.',
    '模块版本号': 'Module version number',
    '模块状态。': 'Module status.',
    '引用计数。': 'Reference count.',
    '上下文内存字节数。': 'Context memory byte count.',
    '动态内存块个数。': 'Number of dynamic memory blocks.',
    '设置的最大通道数。': 'Maximum number of channels set.',
    '设置的最大像素宽度。': 'Maximum pixel width set.',
    '设置的最大像素高度。': 'Maximum pixel height set.',
    '1帧最大支持Slice数。': 'Maximum number of slices supported per frame.',
    '设置的VDH可支持的并行解码帧数，有效范围[1, 8]，超出有效范围：按最大支持并行解码帧数设置。': 'Number of parallel decode frames supported by VDH. Valid range [1, 8]. Out of range: set to maximum supported parallel decode frames.',
    '上下文内存边界校验码。': 'Context memory boundary check code.',
    '1234abcd：正常；': '1234abcd: Normal;',
    '其他：异常。': 'Other: Abnormal.',
    '独立标示号。': 'Unique identifier.',
    '通道优先级。': 'Channel priority.',
    '最大像素宽度。': 'Maximum pixel width.',
    '最大像素高度。': 'Maximum pixel height.',
    '图像解码模式。': 'Image decode mode.',
    '0：IPB模式；': '0: IPB mode;',
    '1：IP模式；': '1: IP mode;',
    '2：I模式。': '2: I mode.',
    '图像输出模式。': 'Image output mode.',
    '0：显示序输出；': '0: Display order output;',
    '1：解码序输出。': '1: Decode order output.',
    '是否支持Linear': 'Whether Linear is supported',
    '0：不支持；': '0: Not supported;',
    '1：支持。': '1: Supported.',
    '图像压缩标志。': 'Image compression flag.',
    '0：不压缩；': '0: No compression;',
    '1：Tile压缩。': '1: Tile compression.',
    '图像输出错误率阈值。': 'Image output error rate threshold.',
    '0：错误图像都不输出；': '0: Do not output any erroneous images;',
    '100：所有图像都输出；': '100: Output all images;',
    '1~99：错误率大于阈值不输出。': '1~99: Do not output if error rate exceeds threshold.',
    '输入低延迟解码标志。': 'Input low delay decode flag.',
    '0：不使能输入低延迟解码；': '0: Disable input low delay decode;',
    '1：使能输入低延迟解码。': '1: Enable input low delay decode.',
    '输出低延迟解码标志。': 'Output low delay decode flag.',
    '0：不使能输出低延迟解码；': '0: Disable output low delay decode;',
    '1：使能输出低延迟解码。': '1: Enable output low delay decode.',
    'MDC路径选择。': 'MDC path selection.',
    '0：不使用MDC；': '0: Do not use MDC;',
    '1：使用MDC。': '1: Use MDC.',
    'stop状态计数。': 'Stop state count.',
    'reset状态计数。': 'Reset state count.',
    'User data使能标志。': 'User data enable flag.',
    'User data buffer长度。': 'User data buffer length.',
    '解码协议类型。': 'Decode protocol type.',
    'ADPCM解码时具体的类型。': 'Specific type for ADPCM decoding.',
    '帧缓存数目。': 'Number of frame buffers.',
    'G726解码时的速率。': 'G726 decoding rate.',
    '解码模式。': 'Decode mode.',
    '原始帧发送计数。': 'Original frame send count.',
    '帧发送计数。': 'Frame send count.',
    '帧获取计数。': 'Frame get count.',
    '帧放置计数。': 'Frame put count.',
    '编码协议类型。': 'Encode protocol type.',
    '编码通道属性及状态': 'Encode channel attributes and status',
    '编码通道ID号。': 'Encode channel ID number.',
    'ADPCM编码时具体的类型。': 'Specific type for ADPCM encoding.',
    '每帧的编码采样点个数。': 'Number of encode sample points per frame.',
    'LBPLC buffer大小。': 'LBPLC buffer size.',
    'G726编码速率。': 'G726 encode rate.',
    '接收帧计数。': 'Received frame count.',
    'Ai缓存失帧计数。': 'AI buffer frame loss count.',
    '编码成功计数。': 'Encode success count.',
    '编码数据帧错误计数。': 'Encode data frame error count.',
    'Buffer满计数。': 'Buffer full count.',
    '获取码流计数。': 'Stream get count.',
    '释放码流计数。': 'Stream release count.',
    '编码静音标志。': 'Encode mute flag.',
    'n：未静音；': 'n: Not muted;',
    'y：静音。': 'y: Muted.',
    '音频解码通道属性及状态': 'Audio decode channel attributes and status',
    '通道号。': 'Channel number.',
    'VDEC支持的最大解码通道数。': 'Maximum number of decode channels supported by VDEC.',
    'Linux系统可通过加载ssxxx_vdec.ko或ssxxx_ vdec.ko时设置模块参数g_vdec_max_chn_num配置。': 'On Linux systems, this can be configured by setting the module parameter g_vdec_max_chn_num when loading ssxxx_vdec.ko or ssxxx_vdec.ko.',
    '是否使用码流Buffer省内存模式。': 'Whether to use stream buffer memory saving mode.',
    '0：不使用；': '0: Not used;',
    '1：使用。（注意：码流Buffer省内存模式只有在帧模式解码下有效）': '1: Used. (Note: Stream buffer memory saving mode is only valid in frame mode decoding)',
    '解码帧存分配方式。': 'Decode frame buffer allocation method.',
    '解码兼容模式。': 'Decode compatibility mode.',
    '0：普通模式；': '0: Normal mode;',
    '1：兼容模式，兼容编码跳帧参考配置错误的码流，会额外多使用一个帧存。': '1: Compatibility mode, compatible with streams that have incorrect encoding frame skip reference configuration, uses one additional frame buffer.',
    '0：用户。': '0: User.',
    '最大解码宽度。': 'Maximum decode width.',
    '最大解码高度。': 'Maximum decode height.',
    '允许的最多参考帧数。': 'Maximum number of reference frames allowed.',
    'TMV使能。': 'TMV enable.',
    'y：使能；': 'y: Enable;',
    'n：不使能。': 'n: Disable.',
    '错误容忍度。': 'Error tolerance.',
    '解码模式。': 'Decode mode.',
    'IPB：IPB模式；': 'IPB: IPB mode;',
    'IP：IP模式；': 'IP: IP mode;',
    'I：I模式。': 'I: I mode.',
    '图像输出顺序。': 'Image output order.',
    'DISPLAY：显示序；': 'DISPLAY: Display order;',
    'DECODE：解码序。': 'DECODE: Decode order.',
    '图像压缩方式。': 'Image compression method.',
    'n：不压缩；': 'n: No compression;',
    't：tile压缩。': 't: Tile compression.',
    '视频格式。': 'Video format.',
    'VPS最大个数。': 'Maximum number of VPS.',
    'SPS最大个数。': 'Maximum number of SPS.',
    'PPS最大个数。': 'Maximum number of PPS.',
    '最大Slice段个数。': 'Maximum number of slice segments.',
    '复合解码使能。': 'Composite decode enable.',
    '快速标记模式。': 'Quick mark mode.',
    'ADAPT：自适应；': 'ADAPT: Adaptive;',
    'FORCE：强制。': 'FORCE: Force.',
    '部署模式。': 'Deployment mode.',
    '像素格式。': 'Pixel format.',
    'Alpha值。': 'Alpha value.',
    '图像输出错误率阈值。': 'Image output error rate threshold.',
    '通道工作模式。': 'Channel working mode.',
    '帧buffer满的次数。': 'Frame buffer full count.',
    '用户态发送时的丢帧数。': 'Frame loss count during user-space transmission.',
    '用户设置的音频帧缓存深度。': 'User-set audio frame buffer depth.',
    '通道Buffer中第一个32位数据是否为静音数据。': 'Whether the first 32-bit data in the channel buffer is mute data.',
    '通道Buffer中第二个32位数据是否为静音数据。': 'Whether the second 32-bit data in the channel buffer is mute data.',
    '用户获取的帧计数': 'User frame get count',
    '用户释放的帧计数。': 'User frame release count.',
    '该通道是否启用了重采样功能。': 'Whether resampling is enabled for this channel.',
    '该通道重采样时，输入给重采样的数据帧中包含的采样点数目。': 'Number of sample points in the input data frame for resampling.',
    '该通道重采样时，输入给重采样的数据帧的采样率。': 'Sample rate of the input data frame for resampling.',
    '该通道重采样时，重采样后的音频帧采样率。': 'Sample rate of the resampled audio frame.',
    '记录当前VFMW当前解码通道的使用状况及其属性配置。可用于检查属性配置以及当前解码通道统计状态。': 'Records current VFMW decode channel usage and attribute configuration. Can be used to check attribute configuration and current decode channel statistics.',
    '记录当前解码通道的使用状况及其属性配置。可用于检查属性配置以及当前解码通道统计状态。': 'Records current decode channel usage and attribute configuration. Can be used to check attribute configuration and current decode channel statistics.',
    '记录当前acodec输入输出音量状态信息。': 'Records current acodec input/output volume status information.',
    '记录当前AO属性配置以及状态信息。': 'Records current AO attribute configuration and status information.',
    'AI设备号。': 'AI device number.',
    'AI工作模式。': 'AI working mode.',
    'AO设备号。': 'AO device number.',
    'AO工作模式。': 'AO working mode.',
    'AO设备静音功能是否开启。': 'Whether the AO device mute function is enabled.',
    'AO设备的输出音量大小。': 'AO device output volume level.',
    'AO通道号。': 'AO channel number.',
    '通道buffer的读指针。': 'Channel buffer read pointer.',
    '通道buffer的写指针。': 'Channel buffer write pointer.',
    '帧buffer空的次数。': 'Frame buffer empty count.',
    'AO设备的声道模式。': 'AO device channel mode.',
    'AI设备的声道模式。': 'AI device channel mode.',
    '静音是否开启标志，对AI设备无效。': 'Mute flag. Invalid for AI devices.',
    '音量大小，对AI设备无效。': 'Volume level. Invalid for AI devices.',
    'DMA buffer的物理地址。': 'Physical address of the DMA buffer.',
    'DMA buffer的大小。': 'DMA buffer size.',
    'DMA buffer的读指针相对于起始地址的偏移量。': 'Offset of the DMA buffer read pointer from the start address.',
    'DMA buffer的写指针相对于起始地址的偏移量。': 'Offset of the DMA buffer write pointer from the start address.',
}

for k, v in sorted(translations.items(), key=lambda x: -len(x[0])):
    content = content.replace(k, v)

# Also handle "的" patterns
content = content.replace('的', ' of ')
content = content.replace('图像', 'image ')
content = content.replace('音频', 'audio ')
content = content.replace('参数', 'parameter ')
content = content.replace('属性', 'attribute ')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Translation applied. Output: {path}')
